script/ddgc_release.sh
New instance needs a couple of changes to the deploy script.
I should have removed the backup part last time I amended this...
@malbin
=> Release script updates

src/ia/js/IAPage.js, src/templates/devinfo.handlebars
CC @russellholt as discussed in https://github.com/duckduckgo/community-platform/pull/419#issuecomment-68543391
=> IAPage: Remove "Show More" for now.

src/templates/screens.handlebars
CC @russellholt as discussed in https://github.com/duckduckgo/community-platform/pull/419#issuecomment-68475505
=> IAPage: Remove "Edit" button.

src/templates/devinfo.handlebars
Switch the two around for aesthetic reasons.
=> IAPage: Switch Github Files and Issues around.

templates/instantanswer/ia.tx
When logged in we see an edit button. Since we're it's not working, we're going to remove it for now.
=> IAPage: Remove edit button when logged in.

templates/instantanswer/index.tx
=> IAIndex: Remove the topic class in the filter list.

src/ia/js/IAIndex.js
Show the exact number of IAs in the list.
=> IAIndex: Show the number of items in the header.

package.json
@jdorweiler @russellholt Please let me know if the version pinning is appropriate.
=> Adding grunt-available-tasks and grunt-bump to package.json

src/ddgc/css/feedback.css
=> Changing font URLs to absolute path.

src/ia/js/IAPage.js, src/templates/github.handlebars
This PR does two things:
- Chooses Github
- Completes the URL if all we have is the handle of the service.
=> IAPage: Choose Github over other services.

src/ia/js/DDH.js, src/ia/js/IAIndex.js, src/ia/js/IAPage.js, src/ia/js/ready.js
=> Comment out console.logs

lib/DDGC/DB/Base/Result.pm, lib/DDGC/DB/Result/InstantAnswer/Topics.pm, lib/DDGC/DB/Result/InstantAnswer/Users.pm, script/iameta.pl
@jbarrett @russellholt 
Deletes everything before updating
=> delete all tables options for iameta

lib/DDGC/DB/Result/InstantAnswer/Blocks.pm, lib/DDGC/DB/Result/InstantAnswer/Issues.pm
@russellholt @MariagraziaAlastra @jbarrett  These two also need the cascade option turned on.  You will have to do the ddgc_db_autoupgrade after this is merged though.
=> add more cascade options

src/ia/js/IAIndex.js
@russellholt @jagtalon Now it displays the correct count. 
I've tested it, but I'd like you to test it too. Let's make sure there are no edge cases.
=> IA Pages Index - Fix the count for "All Topics"

src/ia/css/ia.css
Very small changes to the IAPage. All changes to font sizes and spacing and color.
=> ia.css: A few small changes in the IAPage

src/ia/css/ia.css
=> IAPage: Don't let the name overflow.

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/ia/js/IAPage.js, src/ia/js/IAPageCommit.js, src/templates/commit_page.handlebars, src/templates/edit_description.handlebars, src/templates/edit_examples.handlebars, src/templates/edit_name.handlebars, src/templates/edit_status.handlebars, src/templates/edit_topic.handlebars, src/templates/pre_edit_description.handlebars, src/templates/pre_edit_examples.handlebars, src/templates/pre_edit_name.handlebars, src/templates/pre_edit_status.handlebars, src/templates/pre_edit_topic.handlebars, templates/instantanswer/ia.tx
After a massive refactoring, page editing is back.
The layout is totally different and independent from the static page one, but it uses the same principle as before: when clicking on the edit button, the page gets replaced by the pre_edit Handlebars templates, one for each editable field, shaping what I like to call the "Diff View", in which you can see the live version vs the edited one for each field:
To edit a field, just click on "Edit" at the top-right corner of the row, and the entire row will be highlighted in green, and under the "Edited" column will show up an input containing either the latest edit for that field, if available, otherwise the live version. To save just hit "return" on the keyboard or click on "Done" on the top-right corner of the row:
Topics and examples have a …
=> IA Pages - bring back page editing

src/ia/css/ia.css
CC @MariagraziaAlastra 
Old:
New:
It could use some help distinguishing the individual queries, but it works and we can circle back to that.
=> IA Page: Prevent text from overlapping.

src/ia/css/ia.css, src/ia/js/IAPage.js, src/templates/edit_description.handlebars
For more space. @MariagraziaAlastra 
Needs some styling help, but here's how it looks at the moment:
Here's how it used to look:
I can improve the style in another PR.
=> IA Page: Replace <input> with <textarea>

cpanfile
Attempting to fix Travis CI builds.
=> Adding Test::EOL to prereqs.

script/ghIssues.pl
Switched ghIssues script to use HTTP::Tiny
@jbarrett @MariagraziaAlastra @russellholt
=> use HTTP::Tiny

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/js/IAPage.js
@jagtalon @russellholt see comments on #475
=> IA Pages - hide toggle-view button if there aren't edits

src/ia/css/ia.css
=> IA Pages - tweaks on the textarea css

lib/DDGC/Web/Controller/Forum/My.pm, templates/i/comment/thread.tx
=> Expose thread delete button to community leaders.

lib/DDGC/Web/Controller/InstantAnswer.pm
See comments on #484 
@russellholt @jdorweiler @jbarrett
=> InstantAnswer.pm - use search() to get multiple rows for issues

lib/DDGC/Web/Controller/Translate.pm, templates/translate/tokenlanguage.tx, templates/translate/tokens/token_language.tx
dx4 is a fix for the performance of #486.
(Sorry, won't happen again) :smile:
=> Fix token note submission in browse view.

script/ghIssues.pl
The delete/update is done in a transaction so it will roll back on any errors.  
@MariagraziaAlastra @russellholt @jbarrett
=> ghissues regex bug and added transactions 

src/ia/css/ia.css
Here's how it used to look:
If you notice, the live columns in "Other Queries" and "Topics" are not aligned properly. One solution is to vertically align them so that the list is centered in the middle:
But it was a bit difficult to pull off. So to put in the least amount of changes, I did this instead:
I think it does the job, but tell me what you think @MariagraziaAlastra!
=> IAPages: Align the lists

src/ia/css/ia.css, src/templates/in_development.handlebars, src/templates/planning.handlebars, src/templates/qa.handlebars, src/templates/ready.handlebars
@MariagraziaAlastra Made some changes to make it look like the mockup that we talked about:
I haven't done anything with regards to showing which one is the current milestone--maybe it should be colored green?
So, yeah, still a work in progress but would love some initial feedback (or if I broke something). Screenshots:
Arbitrary text works, but kinda gross that it changes the height of just one card.
=> Dev Page: Initial styling for the dev page

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/ia/js/IAPage.js, src/templates/description.handlebars, src/templates/edit_dev_milestone.handlebars, src/templates/in_development.handlebars, src/templates/name.handlebars, src/templates/planning.handlebars, src/templates/qa.handlebars, src/templates/ready.handlebars
WIP, will add Handlebars templates afterwards; @jagtalon will help, so he's going to make some PRs to this branch.
//cc @russellholt
=> IA Pages - load different templates on the static page based on the dev milestone

script/ddgc_release.sh
=> Ensure release script only uses pinto mirror.

lib/DDGC/Web/Controller/InstantAnswer.pm
=> InstantAnswer.pm - fetch only IAs with dev milestone = 'live' for the index

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, templates/instantanswer/index.tx
Coming Soon IAs are the ones which have the "ready" dev milestone.
Screenshots:
(On my instance Airlines has the "ready" dev milestone)
=> IA Pages Index - show coming soon IAs and bring back filters for the dev milestone

src/ia/css/ia.css, src/ia/js/IAPage.js, src/templates/planning.handlebars
I'm logged in as "cpan", which is the specified username for the producer field, so the button is hidden for that one:
=> Dev IA Page - add 'assign to me' buttons for team roles

templates/wear.tx
@zekiel Front page butchered, don't tell @sdougbrown :)
If you haven't done phase 1:
=> Closing /wear

src/ia/js/IAPage.js
@jagtalon Tested and WFM, could you please confirm everything works as expected before merging?
=> IA Page - fix bug with live-edited switch toggle

src/templates/commit_page.handlebars
@jagtalon @russellholt Hope it's clear enough. If it's not, any suggestion about better phrasing is welcome!
=> IA Pages - add explanatory paragraph to the commit page

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/ia/js/IAIndex.js, src/ia/js/IAPage.js, templates/instantanswer/index.tx
=> IA Pages - add 'New IA Page' button and form to the Index

Gruntfile.js, lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/ia/js/IADevPipeline.js, src/templates/dev_pipeline.handlebars, templates/instantanswer/dev_pipeline.tx
WIP! I'd like to get at least some basic layout done before merging this.
=> IA Pages - Add endpoints for the Dev Pipeline

src/templates/pre_edit_description.handlebars, src/templates/pre_edit_dev_milestone.handlebars, src/templates/pre_edit_example_query.handlebars, src/templates/pre_edit_name.handlebars, src/templates/pre_edit_other_queries.handlebars, src/templates/pre_edit_status.handlebars, src/templates/pre_edit_topic.handlebars
=> IA Pages - edit mode - add fallback text for missing live values

src/ia/js/IAPage.js, src/templates/name.handlebars
=> IA static Pages - fix bug with live-edited switch for status

src/ia/js/IAPage.js
@russellholt As discussed, no need to reload the page now.
=> IAPage.js - change input value after clicking on 'assign to me'

sql/1.012/cascasde_topics.sql
@jbarrett sql for the topics table cascade delete.
=> Topics sql

src/ia/js/IAPage.js, src/templates/planning.handlebars
=> Dev IA Pages - replace input with dropdown on the repo section

lib/DDGC/Web/Controller/InstantAnswer.pm
=> InstantAnswer.pm - get topics on the repo JSON endpoint

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/ia/js/IAPage.js, src/templates/planning.handlebars
@russellholt data returned from the JSON endpoint after saving:
```json
"src_options":{
"skip_end":0,
"skip_abstract":1,
"skip_qr":0,
"skip_image_name":0,
"skip_icon":0,
"directory":"test",
"min_abstract_length":"10",
"skip_abstract_paren":1,
"is_wikipedia":0,
"src_info":"",
"is_mediawiki":0
}
```
Screenshot:
=> Dev Pages - show Fathead-specific section

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/ia/js/IADevPipeline.js, src/templates/dev_pipeline.handlebars, src/templates/dev_pipeline_live.handlebars, templates/instantanswer/dev_pipeline.tx
=> Dev Pipeline - Add a view for live IAs which have issues

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/js/IAPage.js, src/templates/planning.handlebars, src/templates/qa.handlebars
The main thing is that now you can delete values, and then there's some other fix like the test machine url one.
=> Dev Page - bug fixes and improvements

src/templates/qa.handlebars
=> Dev Page - use dropdown for test machine field

lib/DDGC/Web/Controller/My.pm, sql/1.014/email-valid.pl
- Store `Email::Valid` email address on registration / email change
- Do the same for existing email addresses
=> Email validation - store Email::Valid email

src/ia/js/Helpers.js
=> Helpers.js - check tab is defined before checking length

lib/DDGC/Web/Controller/InstantAnswer.pm
@jagtalon Now you should get sorted topics on the dev page :)
=> InstantAnswer.pm - sort topics alphabetically on the dev page, too

lib/DDGC/Web/Controller/InstantAnswer.pm
@russellholt @moollaza as requested, now you should get redirected to the default dev pipeline view :)
=> InstantAnswer.pm - make ia/pipeline/ redirect to ia/pipeline/dev

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/ia/js/IAPage.js, templates/instantanswer/ia.tx
@russellholt @jdorweiler 
[Screencast](http://gfycat.com/WarmheartedAcceptableCony)
=> Dev Page - switch from editable to static view without logging out

lib/DDGC/DB/Result/InstantAnswer/Issues.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, script/ghIssues.pl, src/ia/css/ia.css, src/ia/js/Helpers.js, src/ia/js/IADevPipeline.js, src/templates/dev_pipeline_live.handlebars
@russellholt [Screencast](http://gfycat.com/AnnualEarlyFattaileddunnart)
=> Dev Pipeline - live view - filter by issue tags

lib/DDGC/Web/Controller/Campaign/SubmitResponse.pm, templates/wear.tx
We have the rubber stamp already. Old revisions back in style!
WATCH OUT, COMING THROUGH!
=> Open campaign

src/ia/css/ia.css, src/ia/js/IAPage.js, src/templates/in_development.handlebars, src/templates/metafields.handlebars
=> Dev Page - move topic and tab name to metafields.handlebars

src/ia/css/ia.css, src/ia/js/IAPage.js, templates/instantanswer/ia.tx
=> Dev Page - add 'View as JSON' button for users with permissions

src/ia/css/ia.css, src/ia/js/IAPage.js, src/templates/in_development.handlebars, src/templates/planning.handlebars, src/templates/qa.handlebars, src/templates/ready.handlebars
=> Dev Page - add screenshot and organize dev milestones panels vertically

src/ia/js/IAPage.js
@russellholt Fixes empty dropdowns
=> Dev Page - add allowed topics after appending metafields.handlebars

lib/DDGC/DB/Result/InstantAnswer/Issues.pm, script/ghIssues.pl, sql/1.020/issue_dates.sql
@russellholt @MariagraziaAlastra
=> add issue dates

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/js/IAPage.js, src/templates/edit_designer.handlebars, src/templates/edit_developer.handlebars, src/templates/edit_perl_module.handlebars, src/templates/edit_producer.handlebars, src/templates/edit_tab.handlebars, src/templates/edit_template.handlebars, src/templates/handlebars_tmp, src/templates/pre_edit_designer.handlebars, src/templates/pre_edit_developer.handlebars, src/templates/pre_edit_perl_module.handlebars, src/templates/pre_edit_producer.handlebars, src/templates/pre_edit_tab.handlebars, src/templates/pre_edit_template.handlebars
@russellholt first bunch of new fields for the editable page (need to add some other fields in other PRs)
=> IA Pages - add new fields to the editable page

src/ia/css/ia.css
=> ia.css - the 'live' dev milestone should have green text and borders

src/templates/edit_topic.handlebars
@jdorweiler this means everyone will be able to add topics even on IAs which don't have them. It's specifically three because we decided that's the max number of topics we're going to allow for an IA.
//cc @russellholt
=> IA Pages - always show three dropdowns for topics on the editable view

src/templates/commit_page.handlebars
=> commit_page.handlebars - update with newly added fields

src/ia/js/Helpers.js, src/templates/name.handlebars
=> IA Pages - remove underscore from in_development dev milestone

src/ia/css/ia.css, src/ia/js/IAPage.js, src/templates/in_development.handlebars, src/templates/metafields.handlebars, src/templates/planning.handlebars, src/templates/qa.handlebars
=> Dev IA Pages - move fields to the header

src/templates/github.handlebars
=> IA Pages - make use of the developer column for attribution

lib/DDGC/Web/Controller/InstantAnswer.pm
add attribution .. we may change the structure of it but for now we need it for the metadata publishing
=> add attribution to repo json

lib/DDGC/DB/Result/InstantAnswer/Issues.pm, script/ghIssues.pl, sql/1.021/author.sql
=> Author in issues table

lib/DDGC/Web/Controller/InstantAnswer.pm, src/templates/github.handlebars, src/templates/metafields.handlebars
=> Dev IA Pages - use the author column from instant_answer_issues to fill the developer column if empty

src/ia/js/IADevPipeline.js
@russellholt As in the title, quite straightforward. Merging
=> IADevPipeline.js - strip spaces from ID on new IA Page creation

src/ia/css/ia.css, src/templates/metafields.handlebars
Put things in a table to match the mockup:
Screenshot:
Only thing missing is the boarder though. CC @MariagraziaAlastra
=> Dev Pipeline: Make the header look better.

src/ia/css/ia.css, src/ia/js/IAPage.js
=> Dev IA Page - hide screenshot and rearrange the page layout accordingly on img error

lib/DDGC/Web/Controller/InstantAnswer.pm, src/templates/commit_page.handlebars, src/templates/edit_developer.handlebars, src/templates/pre_edit_developer.handlebars
@russellholt Bug fix, merging right away
=> IA Pages - handle the new developer column structure correctly across endpoints

src/templates/metafields.handlebars
=> metafields.handlebars - display ID and add label for description

src/templates/screens.handlebars
=> screens.handlebars - drop fake links for IAs in development

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/ia/js/IAPage.js, src/ia/js/IAPageCommit.js, src/templates/commit_page.handlebars, src/templates/edit_answerbar.handlebars, src/templates/edit_other_queries.handlebars, src/templates/edit_perl_dependencies.handlebars, src/templates/edit_src_api_documentation.handlebars, src/templates/edit_src_options.handlebars, src/templates/edit_triggers.handlebars, src/templates/edit_unsafe.handlebars, src/templates/pre_edit_answerbar.handlebars, src/templates/pre_edit_perl_dependencies.handlebars, src/templates/pre_edit_src_api_documentation.handlebars, src/templates/pre_edit_src_options.handlebars, src/templates/pre_edit_triggers.handlebars, src/templates/pre_edit_unsafe.handlebars
WIP, still missing a bit of functionality there
=> IA Pages - editable page - add new fields

src/ia/js/IAPage.js, src/templates/edit_src_options.handlebars
@russellholt Fixes yesterday's weirdness, merging
=> IA Pages - editable page - interact with checkboxes only on edit button click

lib/DDGC/Web/Controller/InstantAnswer.pm
=> InstantAnswer.pm - don't leave out IAs without topics in the Index

src/ia/js/IAPage.js
@russellholt ...So that the select elements for topics are always three. Also removed a bit of unused code, merging right away
=> IA Pages - remove just the selected value instead of the whole element for topics

src/ia/js/IAPageCommit.js, src/templates/commit_page.handlebars
=> Commit Page - don't select any version by default and disable commit button until a version for each field is selected

src/ia/css/ia.css
=> ia.css - avoid overflow on readonly divs in the dev page

src/ia/js/Helpers.js, src/ia/js/IAPage.js, src/templates/edit_unsafe.handlebars, src/templates/pre_edit_unsafe.handlebars
=> IA Pages - editable page - fix the unsafe field editing

lib/DDGC/Web/Controller/InstantAnswer.pm, src/templates/commit_page.handlebars
=> InstantAnswer.pm - commit_json - decode JSON when retrieving src_options

templates/i/user/username.tx, templates/userpage/home.tx
Pass headline to this include instead.
Thanks to @KNTRO for digging this up.
=> Don't skip username include if userpage headline is set.

src/ia/js/Helpers.js, src/ia/js/IAPage.js, src/templates/commit_page.handlebars
=> IA Pages - editable page - allow values removal

sql/1.031/unsafe.sql
=> set unsafe column to zero

lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, sql/1.031/meta_id.pl, sql/1.031/meta_id.sql, src/ia/css/ia.css, src/ia/js/IAPage.js, src/ia/js/IAPageCommit.js, src/templates/commit_page.handlebars, src/templates/dev_pipeline.handlebars, src/templates/dev_pipeline_deprecated.handlebars, src/templates/dev_pipeline_live.handlebars, src/templates/edit_meta_id.handlebars, src/templates/index.handlebars, src/templates/metafields_content.handlebars, src/templates/pre_edit_meta_id.handlebars, templates/scripts.tx
=> IA Pages - add meta_id column (editable ID)

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/ia/js/IAPage.js, src/templates/in_development_content.handlebars, src/templates/metafields_content.handlebars, src/templates/planning_content.handlebars, src/templates/qa_content.handlebars, src/templates/ready_content.handlebars
@russellholt [Screencast 1](http://gfycat.com/FortunateHalfAplomadofalcon)
[Screencast 2](http://gfycat.com/GrouchyLeanGrebe)
=> Dev IA Pages - make visually clear whether a value is saved or not

src/templates/in_development_content.handlebars, src/templates/planning_content.handlebars
@russellholt @moollaza As you requested!
=> Dev IA Pages - move template field to planning

lib/DDGC/Web/Controller/My.pm
Thanks @russellholt for the heads up.
=> Fix occasional 'uninitialized value' error in My.pm

lib/DDGC/Web/Controller/Translate/Po.pm, templates/email/newpo.tx
Same as duckpan upload, have poupload mail a link + the filename for review to the uploader.
=> Email uploader when a new PO file is uploaded.

lib/DDGC/Web/Controller/InstantAnswer.pm
@russellholt @jagtalon So they can be deployed on test machines when in QA
=> InstantAnswer.pm - get live, ready and qa IAs in the repo JSON endpoint

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/templates/dev_pipeline.handlebars
=> Dev Pipeline - show types by IA names

lib/DDGC/DB/Result/InstantAnswer.pm
=> add fathead src_domain to json endpoint

lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/ia/js/IAPage.js, src/templates/commit_page.handlebars, src/templates/edit_id.handlebars, src/templates/edit_meta_id.handlebars, src/templates/metafields_content.handlebars, src/templates/pre_edit_id.handlebars
=> IA Pages - show meta_id as id in the JSON endpoints and update frontend accordingly

src/templates/index.handlebars
@russellholt Needed for the links to the single IA Pages
=> index.handlebars - replace meta_id with id

lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/js/IAPage.js, src/ia/js/IAPageCommit.js, src/templates/commit_page.handlebars, src/templates/edit_src_domain.handlebars, src/templates/edit_src_id.handlebars, src/templates/edit_src_name.handlebars, src/templates/planning_content.handlebars, src/templates/pre_edit_src_domain.handlebars, src/templates/pre_edit_src_id.handlebars, src/templates/pre_edit_src_name.handlebars
=> IA Pages - edit src_id, src_name and src_domain

lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/js/IADevPipeline.js, src/templates/dev_pipeline.handlebars, src/templates/dev_pipeline_deprecated.handlebars, src/templates/dev_pipeline_live.handlebars
=> Dev Pipeline - make use of custom column attributes, fix meta_id and developer values

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/css/ia.css, src/templates/dev_pipeline.handlebars
=> Dev Pipeline - highlight IAs the user can edit

lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, sql/1.033/dates.sql
Adds a date for when an IA goes from planning to in_development and a date when it goes from ready to live.
=> milestone dates

lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, sql/1.033/created_date.sql
=> IA page creation date

src/templates/index.handlebars
Because we don't like to do just one release on Friday
=> index.handlebars - get the screenshot correctly

src/templates/edit_src_options.handlebars
=> edit_src_options.handlebars - fix src_info editing

lib/DDGC/Web/Controller/InstantAnswer.pm, src/ia/js/IAPage.js, src/templates/metafields_content.handlebars
@russellholt Bug fix - on the editable live page the check wasn't performed before saving the staged edit - now it is
=> IA Pages - fix check for meta_id uniqueness

src/ia/js/IAPage.js
@russellholt now it's possible to add multiple items to fields such as triggers, perl dependencies and developer instead of just one at a time
=> IAPage.js - editable page - add unlimited inputs instead of just one for each edit attempt

src/ia/js/IAPage.js, src/templates/metafields_content.handlebars
=> Dev IA Pages - make name editable

lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm
@russellholt @jagtalon @jdorweiler
=> IA Pages - add developer, producer and designer to the repo JSON endpoint and show IAs which are in development

src/ia/js/IAPage.js
@russellholt Added user check on username input focusout, too (previously it was only on return keypress and selected type change)
=> IAPage.js - editable page - check developer username on focusout too

sql/1.036/tabs.sql
=> set goodies tabs to answer

lib/DDGC/Web/Controller/Admin/Stats.pm, templates/admin/stats/coupons.tx, templates/admin/stats/index.tx
@zekiel 
We can make the date formatting anything you like
=> Coupon stats page

Gruntfile.js
=> Gruntfile.js: "grunt release" couldn't find ia.css

script/ddgc_rebuild_dev_db.pl, script/iameta.pl
Truncates all tables and rebuilds with data from `/ia/view/<IA>/json`
=> update dev database with live json data

src/ia/js/Helpers.js, src/ia/js/IAPage.js, src/templates/edit_developer.handlebars, src/templates/edit_repo.handlebars, src/templates/metafields_content.handlebars, src/templates/planning_content.handlebars
=> IA Pages - don't show duplicate values in the dropdowns

lib/DDGC/Web/Controller/InstantAnswer.pm, templates/instantanswer/index.tx
=> IA Pages Index - hide coming soon IAs

src/ia/js/IAPage.js, src/templates/metafields_content.handlebars, templates/instantanswer/ia.tx
@russellholt [Screencast](http://gfycat.com/MeanSleepyCougar)
=> IA Pages - make it possible to select an empty value for test machine and topics

lib/DDGC/DB/Result/InstantAnswer.pm, src/ia/js/IAPage.js, src/templates/commit_page.handlebars, src/templates/edit_is_stackexchange.handlebars, src/templates/planning_content.handlebars, src/templates/pre_edit_is_stackexchange.handlebars, src/templates/pre_edit_src_domain.handlebars, src/templates/pre_edit_unsafe.handlebars
=> IA Pages - add is_stackexchange field and make src_domain editable for longtails

sql/1.038/is_stackexchange.sql
=> Add sql for is_stackexchange field

src/templates/devinfo.handlebars
=> devinfo.handlebars - add IA name in the title when creating an issue and improve link placement

Gruntfile.js
For @MariagraziaAlastra -- I forgot to test this command. :)
=> Gruntfile.js: make `grunt release` work again.

templates/wear.tx
//cc @jbarrett not sure if this will render correctly -- can you verify on your box before releasing?
=> updated text

src/js/ia/IAPage.js, src/scss/ia/_ia.scss, src/templates/screens.handlebars
Here's a video: https://vid.me/eixe
=> Screenshot: Disable button if there is no test machine or not live.

.travis.yml
Let's see if travis builds this :)
=> Specify CPAN and DuckPAN mirrors for installdeps and authordeps

lib/DDGC/Web.pm, lib/DDGC/Web/Controller/Campaign/SubmitResponse.pm, lib/DDGC/Web/Controller/Duckpan.pm, lib/DDGC/Web/Controller/Feedback.pm, lib/DDGC/Web/Controller/My.pm, lib/DDGC/Web/Controller/Translate/Po.pm, templates/my/forgotpw.tx
...from dukgo.com to duck.co. The former is causing a little confusion.
=> Change noreply@ address

lib/DDGC/DB/Result/User.pm, lib/DDGC/Web/Controller/Admin/User.pm, templates/i/user/admin.tx
=> Admin option to unsub a user from all notification

templates/blog/sidebar.tx
=> sidebar.tx: Change link to duck.co

share/docroot/error.html
I found a few more of the old StickerMule links, applying same correction to all.
=> Correction for DDG StickerMule Marketplace

lib/DDGC/Web/Controller/InstantAnswer.pm
Fixes the PR link on the in-development IA pages
=> github PR links

script/ghIssues.pl
1. Check for "New Instant Answer" label
2. set dev_milestone to planning
3. `DDG::Goodie::CheatSheets` for stuff that has a cheat sheet looking name.
=> only add new page for new ia label and fix cheat sheet perl module

lib/DDGC/DB/Result/User/CampaignNotice.pm
=> Don't return an address for apparently deleted users.

root/static/css/content.css, src/scss/ia/_dev.scss, src/scss/ia/_ia.scss, src/templates/advanced_content.handlebars, src/templates/base_info_content.handlebars, src/templates/contributors_content.handlebars, src/templates/metafields_content.handlebars
Round 2 of dev pages improvements
=> IA Dev Page - more improvements

src/js/ia/IAPage.js, src/templates/name.handlebars
Previously the name disappeared when switching between "live" and "edited" on the live static page - now it doesn't :)
=> IA Pages - fix switching between live and edited view inside name.handlebars

templates/instantanswer/dev_pipeline.tx
=> dev_pipeline.tx - update milestone values

src/js/ia/IAPage.js
Fixes having all topics deleted when removing a single topic on the dev page
=> IA Dev Page - correct selector for topics

src/js/ia/IAPage.js
Fixes disappearing list item when changing type with void input value
=> IA Dev Page - don't try to save on type change if both username and type aren't set

lib/DDGC/Web/Controller/InstantAnswer.pm
Fixes the messed up encoding in the updates table.
=> use to_json and from_json

sql/1.043/ddg-attribution.sql
Add developer info to any IA that doesn't already have it.
=> added ddg attribution

root/static/css/content.css, src/js/ia/IAPage.js, src/scss/ia/_dev.scss, src/scss/ia/_ia.scss, src/templates/advanced.handlebars, src/templates/advanced_content.handlebars, src/templates/screens.handlebars, src/templates/testing.handlebars, src/templates/testing_content.handlebars
Use `thirds` and `twothirds` for widths and `g` and `mg-top--big` for padding instead of writing custom ones.
Has been applied to testing and advanced, but the rest have yet to use these.
=> Use built-in classes to align the columns

lib/DDGC/Web/App/Blog.pm, script/ddgc_dev_server.sh, views/includes/head.tx, views/includes/header/nav.tx, views/layouts/main.tx
Small fixes to blog application styling, templates and login behaviour.
=> Styling fixes

lib/Dancer2/Plugin/DDGC/Session.pm
Set CSRF tokens in session if they're not set
=> Fix login modal on new service pages

templates/my/blog/edit.tx
@zekiel Rather than faff about with tag cusomisation, I updated the help :)
=> Update bbcode help

lib/DDGC.pm
I somehow removed it in 8386f38
=> Restore IO::All to DDGC.pm

lib/DDGC/Web/Controller/My/Blog.pm, lib/DDGC/Web/Service/Blog.pm, lib/Dancer2/Plugin/DDGC/Validate.pm
- Setting fixed date
- Ordering by fixed, created dates rather than ID.
=> Fixes for blog post fixed date

lib/DDGC.pm, lib/DDGC/Web/Controller/My/Blog.pm, lib/Dancer2/Plugin/DDGC/Request.pm, lib/Dancer2/Plugin/DDGC/Validate.pm, templates/my/blog/edit.tx
- Validation fixes
- Retain errors for reporting in 'edit' template
=> Blog post authoring validation and feedback.

lib/DDGC/Web/Controller/Root.pm
nginx will do this from now on.
=> Stop setting CSP headers in code

lib/DDGC/Web/Controller/Campaign/SubmitResponse.pm, lib/DDGC/Web/Controller/Root.pm, root/static/pages/404.html, share/docroot/error.html, share/docroot/maintenance.html
=> Share updates

src/js/ia/IAIssues.js
=> IA Pages - add URL params filtering to the Issues page

lib/DDGC/Web/Controller/InstantAnswer.pm
@russellholt Simple fix for excluding old IA Pages which don't have dates
=> Overview page - exclude IA Pages with undefined dates

lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, src/scss/ia/overview.scss, src/templates/overview.handlebars
@russellholt (only for most recent IAs, when the user isn't logged in/didn't contribute to any IAs yet)
=> Overview Page - show dates next to IA Pages

lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, sql/1.051/01-nullable-columns.sql
@MariagraziaAlastra Please review - thanks!
=> Small typo fixes

templates/wear.tx
=> text changes to footer

lib/DDGC/DB/Result/Language.pm, lib/DDGC/DB/Result/User/Blog.pm, lib/DDGC/Schema/Result/User/Blog.pm, lib/DDGC/Web/Controller/My/Blog.pm, lib/Dancer2/Plugin/DDGC/Validate.pm, sql/1.051/00-blog-new-cols.sql, templates/my/blog/edit.tx
=> Markdown blog posts

lib/DDGC/DB/Result/InstantAnswer.pm
=> Add triggers to repo JSON endpoint

src/templates/issues.handlebars
@russellholt Fixes invalid issues links to GH when sorting by creation date
=> Issues Page - fix repo

templates/feedback/thanks.tx, templates/header_nav.tx, templates/i/user_blog/label.tx, templates/my/account.tx, templates/my/notifications/edit.tx, templates/my/notifications/following.tx, templates/my/userpage/index.tx, templates/translate/domainindex.tx, templates/translate/index.tx
=> Update blog links in templates

src/js/ia/IAIndex.js
@russellholt fixes missing IAs count on the header :)
=> Index Page - call filter() on page load even if no params

lib/DDGC/Web/Controller/InstantAnswer.pm, root/static/css/content.css
@russellholt @moollaza 
Not much to say, now it should be possible to commit an empty value for topics (e.g. if we want to remove all of them from an IA Page)
=> Commit Page - allow removing all topics

src/js/ia/IAIndex.js, src/js/ia/IAIssues.js
@russellholt fixes the regression on the query param.
Leaving this open, I want to remove the first "&" as well
=> IAIndex - fix query URL param

lib/DDGC/DB/Result/InstantAnswer.pm
=> Remove triggers from repo JSON endpoint

lib/DDGC/Schema/Result/User/Blog.pm, lib/DDGC/Web/Controller/My/Blog.pm, lib/DDGC/Web/Service/Blog.pm, templates/my/blog/edit.tx
Based on feedback from @nilnilnil and @b1ake - thanks! Also, some other stuff.
- Allow admins to edit others' posts
- Add notification so you get comments on your posts
- Lose the BBCode buttons, they don't do markdown and were introducing erroneous content.
=> Blog fixes

sql/1.056/nomralize_ddg_attribution.sql
This will change all the "DuckDuckGo" and "duckduckgo" developers to "DDG Team".
=> normalize ddg credits

src/js/ia/IAIndex.js
@moollaza problem solved, now the spaces are represented by the plus sign. :)
=> IA Index - encode/decode query URL param

templates/instantanswer/ia.tx
=> IA Page - fix commit button's position

lib/DDGC/Web/Controller/InstantAnswer.pm
@MariagraziaAlastra Can you confirm this still does what's expected? Thanks.
=> Array-ref sigil typo

lib/DDGC/Web/Controller/InstantAnswer.pm
@jdorweiler Even though it shouldn't be executed anymore I'll merge to master and do another deployment just to be sure
=> InstantAnswer.pm - remove unused and buggy code for setting the developer value

lib/DDGC/DB/Result/Event/Notification/Group.pm, lib/DDGC/Web/Controller/Help.pm, templates/i/event_notification_group/email_comments.tx, templates/i/event_notification_group/reports/email.tx
- Guard against calling methods on null RSes.
- Email rendering fixes (typo'd method call)
=> RS handling fixes

templates/my/account.tx
=> Change translation manager profile page link

lib/DDGC/Web/Controller/InstantAnswer.pm, root/static/css/content.css, src/js/ia/IAPage.js, src/templates/edit_developer.handlebars
@jdorweiler You just need to set the type to "ddg" in the dropdown and everything else will be filled in automatically for you:
After commit:
=> Editable Page - allow adding DDG Team as developer

root/static/css/content.css, src/scss/content/main.scss, src/scss/ia/main.scss
This PR makes sure that all the right SCSS things are imported.
💀 **Don't merge until https://github.com/duckduckgo/litestrap/pull/2 has been merged.** 💀
=> duckduckgo/litestrap has been reorganized.

root/static/pages/404.html, templates/footer.tx, views/includes/footer.tx
@MariagraziaAlastra @russellholt @zekiel Thanks!
=> Replace IRC link with IA Pages index

src/scss/ddgc/_github_stats.scss, templates/admin/stats/github.tx
cc @MariagraziaAlastra @jbarrett
=> rm styling for h1, h2, and a becuase it affects other pages

src/scss/ia/_dev.scss, src/scss/ia/_ia.scss, src/templates/devinfo.handlebars
It's now consistent between the logged out and logged in views. :)
=> Some tweaks to make the spacing consistent

src/js/ia/IAIndex.js
=> IA Index - pass query value to search input, so it gets filtered correctly

src/js/ia/IAPage.js, src/scss/ia/_dev.scss, src/templates/devinfo.handlebars
@jagtalon the close icon needs styling though:
=> Dev Page Redesign - tweaks on the contributors popup

src/js/ia/IAPage.js
Otherwise the new developer value will only be visible on reload.
=> Dev Page Redesign - call updateHandlebars after autocommitting developer field

src/js/ia/IAPage.js, src/templates/advanced.handlebars, src/templates/edit_unsafe.handlebars
@russellholt The issues we encountered should be fixed now
=> Dev Page Redesign - fix details section commit for section-group fields + fallback for live page checkboxes

src/js/ia/IAPage.js
Fixes details section refreshing and also editing the example query after removing it
=> Dev Page Redesign - more fixes

templates/ideas/idea_form.tx
=> Change IA suggestion link to IA Page Index.

lib/DDGC/Util/Email.pm
=> Fix mailer MIME types 

src/scss/ia/_live.scss
This is a better version of https://github.com/duckduckgo/community-platform/pull/800
=> _live.scss: Remove the double horizontal line.

templates/translate/domainsearch.tx
=> Fix token search

lib/DDGC/DB/Result/User.pm, lib/DDGC/Stats/Comleader.pm
=> Deprecate has_flag - user roles no longer stored in serialised column

lib/DDGC/DB/Result/InstantAnswer.pm, script/ghIssues.pl, sql/1.076/last_activity.sql
Added last activity date.
Also added last commit and last comment.  Here's what the data looks like.  Anything else I should get?
```
last_comment = {
user => users name,
date => date of comment,
text => text of comment,
id => id to link back 
};
last_commit = {
diff => link to diff,
user => user name,
date => date,
message => commit message,
};
```
=> Last activity, comments, and commits

script/check_claimed_ideas.pl
This will find all the idea posts that are claimed but don't have an IA page.  Then create the IA page and subscribe the user to notifications for it.
=> claimed ideas without an IA page

script/ghIssues.pl
Cc: @MariagraziaAlastra @jdorweiler 
Thanks!
=> Match id or meta_id from IA Page URI in ghIssues

script/ghIssues.pl
Use retrieved IA id, not result name to update since result name can be meta_id.
Cc: @MariagraziaAlastra @jdorweiler
=> Fix IA PR / issue linking

script/ghIssues.pl
Thanks @jbarrett!
//cc @jdorweiler
=> ghIssues.pl - avoid rolling back updates when the IA doesn't exist

templates/i/idea/view.tx
Cc: @zekiel @tagawa 
This change is live, just submitting for permanent inclusion.
=> Reduce max claims to two

src/templates/devinfo.handlebars
@moollaza Adds the beta dev machine to the dropdown in the Dev Page :)
=> devinfo.handlebars - add 'beta' dev machine

src/js/ia/IAPage.js, src/templates/top_details.handlebars, src/templates/triggers.handlebars
...Plus a fix on the max topics number check.
=> Dev Page - fix keeping unsaved values for triggers

src/js/ia/IADevPipeline.js, src/scss/ia/_dev.scss, src/templates/dev_pipeline.handlebars, templates/instantanswer/dev_pipeline.tx
The search field goes through each name of the IA in the dev pipeline and hides `<li>` elements that don't match.
=> WIP: Add a search bar in the dev pipeline.

Gruntfile.js, bower.json, lib/DDGC/DB/Result/InstantAnswer.pm, src/js/ia/Helpers.js, src/js/ia/IADevPipeline.js, src/scss/content/_global.scss, src/scss/ia/_ia.scss, src/scss/ia/main.scss, src/templates/dev_pipeline.handlebars
Requires moment.js (install it using bower: `bower install`)
@russellholt
=> Dev Pipeline - show elapsed time since last activity

src/scss/ia/_pipeline.scss
Thanks @jagtalon, I totally forgot to add it!
=> add _pipeline.scss

lib/DDGC/Web/Controller/InstantAnswer.pm, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars
=> Dev Pipeline - show PR link if available

script/ghIssues.pl
Assign the producer to whoever is set as the github assignee.  Also one other small improvement I think you will like :smile: 
@MariagraziaAlastra
=> assign producer

src/js/ia/Helpers.js, src/templates/dev_pipeline.handlebars
- Don't show hours/mins/seconds
- Remove "day(s)"
-  Add a title attribute with full date
- Fix timezone issues.
=> Dev Pipeline - elapsed time improvements

src/js/ia/Helpers.js
=> Dev Pipeline - display elapsed time in days

lib/DDGC/Web/Controller/My.pm, templates/my/requestlanguage.tx
Closed #932, making this a hotfix against master
=> Require CSRF for language request form.

lib/DDGC/Web/Controller/Ideas.pm
@russellholt @MariagraziaAlastra Not sure how I managed this, but this change removes ddgc-ia@ from the Cc field.
=> Only mail claimed ideas once.

lib/DDGC/Web/Controller/InstantAnswer.pm
=> InstantAnswer.pm - no need to use a new instance of DDGC for UUID

lib/DDGC/DB/Result/InstantAnswer.pm
cc @MariagraziaAlastra Thanks!
=> Fix IA URLs in activity mail

cpanfile, lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/DB/ResultSet/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, sql/1.083/ia_last_modified.sql
=> Adding Last-Modified header to IA Page requests

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars, templates/instantanswer/dev_pipeline.tx
Now it's possible to select multiple IAs in the Dev Pipeline and change either the dev milestone or the type for all of them.
Still needs some visual tweak, but it's almost done!
=> Dev Pipeline - add actions

lib/DDGC/DB/Result/InstantAnswer.pm, src/js/ia/Helpers.js, src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars, templates/instantanswer/dev_pipeline.tx
TODO: add "clear filters" button, filter by URL params on load, style tweaks.
=> Dev Pipeline - Inclusively filter by producer name, dev name, missing info and query

src/js/ia/Helpers.js, src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars, src/templates/dev_pipeline_stats.handlebars, templates/instantanswer/dev_pipeline.tx
I'll need some help on making it look nice. @MariagraziaAlastra
=> totals and date stats on pipeline page

src/js/ia/Helpers.js
Quick fix for the missing: all filter in the dev pipeline
=> Helpers.js - hotfix for is_false_array helper

src/js/ia/IADevPipeline.js
=> Dev Pipeline - update count when filtering

src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss, templates/instantanswer/dev_pipeline.tx
=> Dev Pipeline - add count for selected items and "deselect all" option

src/scss/ia/_ia.scss, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars
=> Pipeline columns: change font sizes, colors and margins

src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars
Add the `.selected` class to the `li` tag:
Add the `.important` class to the `li` tag:
=> Pipeline Second Iteration

src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss
=> Dev Pipeline - make use of the new class to highlight selected list items

src/js/ia/IADevPipeline.js
So that there's no list items left highlighted
=> IADevPipeline.js - remove selected class when deselecting all items

src/js/ia/Helpers.js, src/js/ia/IADevPipeline.js, src/templates/dev_pipeline.handlebars, templates/instantanswer/dev_pipeline.tx
Also, remove filtering by producer's and developer's name.
=> Dev Pipeline - the missing info filter now includes producer and developer

lib/DDGC/DB/Result/InstantAnswer.pm, src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline_detail.handlebars, templates/instantanswer/dev_pipeline.tx
=> Dev Pipeline - show page detail as a sidebar when selecting a single item

src/scss/ia/_dev.scss, src/scss/ia/_pipeline.scss, templates/instantanswer/dev_pipeline.tx
Continuation of https://github.com/duckduckgo/community-platform/pull/969 but merging to master instead of dev-ia-pages.
=> Search Pipeline Styling

src/scss/ia/_pipeline.scss, src/templates/dev_pipeline_detail.handlebars
Based on https://projects.invisionapp.com/share/ER482O582#/screens/102135940
=> Style the Sidebar ✍

src/scss/ia/_dev.scss
It's not aligning properly. There seems to be a problem with the dropdown on firefox but that's another issue. Works on Webkit browsers.
=> _dev.scss: Don't modify the position anymore

lib/DDGC/DB/Result/InstantAnswer.pm, script/ghIssues.pl, sql/1.090/all_comments.sql
=> get all comments for a PR

src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars
=> Dev Pipeline - multiselect with click + shift

lib/DDGC/DB/Result/InstantAnswer.pm, script/ghIssues.pl, sql/1.090/at_mentions.sql
Stores the last n @mentions from a comment.
=> store all @mentions from last comment

src/js/ia/IADevPipeline.js
=> IADevPipeline - bring back toggleCheck function

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline_actions.handlebars, src/templates/dev_pipeline_detail.handlebars, templates/instantanswer/dev_pipeline.tx
I moved the multiselect actions to a sidebar.
Still need to add more fields to update though!
=> Dev Pipeline - actions sidebar

src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars, templates/instantanswer/dev_pipeline.tx
Also, now the filtering is only inclusive with the query box.
This means you can filter either by priority or missing info + use a query, like in the mockup.
=> Dev Pipeline - use icons for filtering and add count

src/js/ia/IADevPipeline.js
Just a quick fix to make URL params work again.
=> IADevPipeline - fix URL params

src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars, templates/instantanswer/dev_pipeline.tx
=> Dev Pipeline - add at_mentions filter

src/templates/dev_pipeline.handlebars
Fix for false positives leading to PR links in the pipeline when there's no PR.
=> dev_pipeline.handlebars - check pr key exists

src/scss/ia/_pipeline.scss, src/templates/dev_pipeline_detail.handlebars
=> Dev Pipeline - get all comments in the page sidebar

script/ghIssues.pl
Finally making a PR to fix this ghIssues bug.
=> check for patch file

src/js/ia/Helpers.js
Need to check that obj exists otherwise this fails at `obj.length`
=> check for status array

root/static/css/content.css, src/js/ia/IADevPipeline.js, src/scss/content/_global.scss, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline_actions.handlebars
For @MariagraziaAlastra. Currently a WIP.
=> Style the actions sidebar

src/scss/ia/_pipeline.scss
=> Pipeline: Add class that adds a dog ear in the item.

src/js/ia/IADevPipeline.js
- Make it work on the completed column too (just hold shift right from the start if you want to multiselect);
- use preventDefault() so you're not taken out of the page if you accidentally click on the single page link while multiselecting.
=> Dev Pipeline - tweaks on multiselect

lib/DDGC/DB/Result/GitHub/UserLink.pm, lib/DDGC/DB/Result/User.pm, lib/DDGC/DB/ResultSet/GitHub/UserLink.pm, lib/DDGC/Web/Controller/My/Userpage.pm, script/ghIssues.pl, sql/1.095/github_user.sql, sql/1.095/migrate.pl
This is blocking the dev pipeline redesign, so we need this done ASAP.
Assigning to @jbarrett for review, still WIP
=> Github::UserLink - migrate the data and make use of the stored usernames

src/js/ia/IADevPipeline.js, src/scss/_z-index.scss, src/scss/content/_global.scss, src/scss/content/_modals.scss, src/scss/content/main.scss, src/scss/ia/_pipeline.scss, src/scss/ia/main.scss, src/templates/dev_pipeline.handlebars, src/templates/dev_pipeline_stats.handlebars, templates/instantanswer/dev_pipeline.tx
Here's what it currently looks like:
=> Add the blue header

src/js/ia/IADevPipeline.js, src/templates/dev_pipeline.handlebars
Only available to admins - shows all the IAs in which the last PR activity author is not a duck.co admin (and thus need attention)
=> Dev Pipeline - filter by last activity author

src/js/ia/IADevPipeline.js
If one IA is selected while holding shift, we expect multiselection.
So don't show the sidebar yet.
=> IADevPipeline.js - fix blank sidebar

src/js/ia/IADevPipeline.js, src/templates/dev_pipeline.handlebars
To remove a specific filter, click again on it.
To clear all filters, click on the dev pipeline link in the blue header.
=> Dev Pipeline - remove clear filters button

src/js/ia/IADevPipeline.js, src/templates/dev_pipeline.handlebars, src/templates/dev_pipeline_detail.handlebars
Elapsed time is a link to the PR (if still open)
=> Dev Pipeline - remove 'PR' from rows

src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline_detail.handlebars
=> Initial styling of the detail sidebar.

src/scss/ia/_pipeline.scss
=> Style the sort dropdown.

src/js/ia/Helpers.js, src/js/ia/IADevPipeline.js, src/templates/dev_pipeline_detail.handlebars
=> Dev Pipeline - add priority message in the sidebar (only for admins)

lib/DDGC/Web/Controller/InstantAnswer.pm, script/ghIssues.pl, src/js/ia/IADevPipeline.js, src/js/ia/IAOverview.js, src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars, templates/instantanswer/dev_pipeline.tx, templates/instantanswer/overview.tx
- New IA button was moved to the home (/ia/dev)
- Applied blue dog ears
- Removed link from IA name and put it in the link icon instead
- IA on hover style
- Put issue_id in the last_commit JSON
- search GitHub::Pull to know which PRs were closed and which were merged, so we know which icon to use
- Add pr-merged and pr-closed icons
Hover style when PR is open:
Hover style when PR is closed:
=> Dev Pipeline - various improvements

src/scss/ia/_pipeline.scss, src/templates/dev_pipeline.handlebars
- Remove jagged edges from the dog ear.
- Important items are now rounded items again.
=> Several refinements for the pipeline. A work in progress.

src/js/ia/IADevPipeline.js, src/templates/dev_pipeline.handlebars
- Don't show the @ mentions filter to logged out users
- Save description on return keypress + ctrl keypress in the single page sidebar
=> Dev Pipeline - more tweaks

src/templates/github.handlebars
=> IA Page - mention devs when creating an issue

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IADevPipeline.js, src/js/ia/IAPage.js, src/scss/ia/_live.scss, src/templates/dev_pipeline_detail.handlebars, src/templates/edit_buttons.handlebars
=> IA Pages - add asana button

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IAPage.js, src/scss/ia/_live.scss, src/templates/devinfo.handlebars
//cc @jdorweiler 
And also show the beta install status.
Installed:
Not installed:
=> IA Pages - replace the dev machine dropdown with beta install button

lib/DDGC/Web/Controller/InstantAnswer.pm
@MariagraziaAlastra `$server` is declared above in this sub, so just reused it here - presuming this is OK. Thanks!
=> Quash test errors from multiple declaration

script/ddgc_makeadmin.pl, script/ddgc_revokeadmin.pl
=> Fixing management scripts

lib/DDGC/Web/Controller/Root.pm, templates/status.tx
Reports:
- Version
- DB availability
- Prosody availability
=> Simple status page

src/scss/ia/_pipeline.scss
For @MariagraziaAlastra 
Before:
After:
=> Pipeline: Increase width of actions sidebar

script/ghIssues.pl
Need a better way to get comleader status.
=> comment out comleader stuff

src/templates/dev_pipeline_actions.handlebars, src/templates/dev_pipeline_detail.handlebars, src/templates/devinfo.handlebars
=> IA Pages and Pipeline - allow re-installing IAs to beta

lib/DDGCTest/Database.pm
needed to rebuild boxen for john, maria, and russell
=> commented out add_blogs() when rebuilding test db because it doesn't work

script/ddgc_dev_server.psgi
This has been driving me up the wall
=> Fix annoying missing sessions dir

script/ddgc_upload_metadata.sh
- Only mirrors from duck.co if modified
- Uploads to S3 on curl success (includes 304 response)
- Nothing ties this to being run on duck.co
- Should be quiet running unless error occurs - cron suitable
@jkv @zachthompson
=> Script to mirror IA repo_all JSON on S3

src/scss/ia/_pipeline.scss
- From https://github.com/duckduckgo/community-platform/pull/1033
- From https://github.com/duckduckgo/community-platform/pull/1032
- Bug: hovering over IAs without repo doesn't show the link icon
=> Some design fixes

script/ddgc_upload_metadata.sh
Add an option to specify a parameter so it will force the upload to s3.
cc: @jbarrett
=> allow forcing an upload to s3

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IAPage.js, src/js/ia/IAPageCommit.js, src/templates/commit_page.handlebars, src/templates/edit_blockgroup.handlebars, src/templates/edit_deployment_state.handlebars, src/templates/pre_edit_blockgroup.handlebars, src/templates/pre_edit_deployment_state.handlebars, templates/instantanswer/ia.tx
Still need to add deployment_state!
Blockgroup editing and committing (only available to admins):
=> IA Pages - edit blockgroup and deployment_state

Gruntfile.js
I made the mistake of appending it to the unminified file.
=> Gruntfile.js: Append the libs to the minified file.

src/js/ia/IAPage.js
Since we don't have traffic data in this release
=> IAPage.js - comment out unused code, momentarily

src/js/ia/IAPage.js
Trivial fix, just checking for the existence of the edited hash
=> IAPage.js - fix JS error

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IAPage.js, src/templates/devinfo.handlebars
=> IA Dev Page - edit blockgroup

src/js/ia/IAIndex.js
Fix for URL parameters filtering not working in the index page
=> IAIndex.js - URL parameters filtering needs to happen inside .ready()

package.json, src/js/ia/IAPage.js
Previously we were checking for the test_machine value, but since now we're using just the beta server...
=> IA Dev Pages - show screenshot based on install beta status and example query

Gruntfile.js, lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IAOverview.js, src/js/ia/IAPageNew.js, src/scss/ia/_new.scss, src/scss/ia/main.scss, templates/instantanswer/new_ia.tx
=> New IA flow prototype

lib/DDGC/Web/Controller/InstantAnswer.pm, script/ddgc_populate_ia_dev.pl, script/ddgc_rebuild_dev_db.pl
@MariagraziaAlastra I would appreciate if you tried this out, let me know of any problems.
This does UPSERTs rather than nuking and rebuilding so you should be run it safely as often as required.
=> Populate dev IA data from /ia/repo/all/json

src/js/ia/IAPage.js
=> IAPage.js - beta_install doesn't exist for live pages

src/templates/devinfo.handlebars
//cc @moollaza Now the beta link will be updated when you change the example query :)
=> Dev IA Pages - prefer example_query for the beta link

lib/DDGC/DB/Result/User.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, sql/1.106/new_contributor.sql, src/js/ia/IAPage.js, src/scss/ia/_dev.scss, templates/instantanswer/ia.tx
WIP! Needs more styling and better wording
=> IA Pages - next steps overlay for new contributors

sql/1.096/dynamic-blocks.sql
Update fix typo "goodie_exlusive" (should be exclusive!)  @MariagraziaAlastra can we just run the update statement beginning on [line 28](https://github.com/duckduckgo/community-platform/blob/14b195601adc466d45ad816978b2f452ed5318cf/sql/1.096/dynamic-blocks.sql#L28) to fix these?
hi @jdorweiler
=> exlusive [sic]

templates/instantanswer/new_ia.tx
//cc @russellholt @jagtalon description and name come before example query now:
=> new_ia.tx - change fields order

lib/DDGC/Web/Controller/Ideas.pm, templates/email/iaclaim.tx, templates/i/idea/teaser.tx, templates/i/idea/view.tx, templates/ideas/claimed.tx, templates/ideas/sidebar.tx, templates/ideas/unclaimed.tx
I left the db stuff in there, but everything else should be gone.
Erased from existence :christmas_tree:
=> Ideas Forum - remove claiming process

lib/DDGC/Web/Controller/InstantAnswer.pm
When creating an IA from the new IA wizard, the user will automatically get edit permissions.
//cc @russellholt @jagtalon @jdorweiler
=> IA Pages - automatically give edit permissions to user on IA creation

src/js/ia/Helpers.js, src/templates/dev_pipeline.handlebars
=> Dev Pipeline - add beta filter

script/ddgc_upload_metadata.sh, script/traffic.pl
Points s3cmd at usage specific s3cfgs.
=> Use new credentials for S3

Gruntfile.js, bower.json, lib/DDGC/Config.pm, lib/DDGC/Web/Controller/Root.pm, package.json, root/static/css/content.css, src/scss/ia/_overview.scss, src/scss/ia/_pipeline.scss, src/scss/ia/main.scss, templates/scripts.tx
Continuation of https://github.com/duckduckgo/community-platform/pull/1091
=> Improve speed of compiling SCSS files.

lib/DDGC/DB/Result/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm
Set the data source on IA creation (small fix)
=> New IA wizard - set the src_url on IA creation

lib/DDGC/Web/Controller/My.pm, lib/DDGC/Web/Controller/Root.pm, lib/Dancer2/Plugin/DDGC/Session.pm, templates/modal_login.tx, templates/my/forgotpw.tx, templates/my/login.tx, templates/my/register.tx, views/includes/modal_login.tx
- Stop using randomised field names
- Stop using captcha
- Start using CSRF token
Cc: @MariagraziaAlastra @jdorweiler 
Other potential changes coming in separately - I've made the mistake of trying to conflate too many changes in one PR before... One assumption winds up being invalid, all the other work has to go.
=> Login / Reg form changes

src/js/ia/IAPage.js, src/templates/commit_page.handlebars, src/templates/edit_src_url.handlebars, src/templates/pre_edit_src_url.handlebars, src/templates/src_url.handlebars
//cc @jagtalon @russellholt 
Dev Page:
Live Page:
Editable Live Page
Commit Page:
=> IA Pages - show and edit data source

src/scss/ia/_ia.scss, src/scss/ia/_issues-list.scss, src/scss/ia/_overview.scss
=> Some spacing adjustments 💅

src/js/ia/IAPageNew.js, src/scss/ia/_new.scss, templates/instantanswer/new_ia.tx
//cc @jagtalon I'm going to merge this in, so you can start styling it.
I'll add the modals in different PRs.
=> New IA Wizard - types as radio inputs

src/scss/ia/_modal.scss
=> modal.scss - add general modal style

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/Helpers.js, src/js/ia/IADevPipeline.js, src/templates/overview.handlebars
=> IA Overview - show IAs recently installed on beta

lib/DDGC/DB/ResultSet/InstantAnswer.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, src/templates/issues.handlebars
//cc @tagawa @moollaza @jdorweiler 
Thanks @jbarrett for the help with the Index! Totally forgot we moved the JSON to the resultset :no_good: 
Merging, this should get staged today.
=> IA Pages - hide unnecessary IAs in the index + hide closed issues

templates/instantanswer/dev_pipeline.tx
//cc @jagtalon This brings back multiselect on the pipeline
=> dev_pipeline.tx - add again html element used for detecting permissions

lib/DDGC/Web/Controller/InstantAnswer.pm
Just in case we don't get a response back.
=> use try on beta requests

views/includes/modal_login.tx
=> Fix login from blog

lib/DDGC/Web/Controller/InstantAnswer.pm, lib/DDGC/Web/Controller/My.pm, src/js/ia/IAPageNew.js, src/scss/ia/_new.scss, templates/instantanswer/new_ia.tx
Still need to automatically log in (I want to do that from the frontend, so we don't lose the new IA data) after signing up and I also need to handle errors better.
Almost done, though.
@jbarrett Feel free to take a look at the code already :) I made different endpoints for both login and signup from ia/new_ia.
=> New IA wizard - login and signup modals

src/js/ia/IAPageNew.js
Hotfix for staging //cc @jbarrett
=> IAPageNew.js - pass the data to the create_ia func when the user is logged in

src/js/ia/IAPageNew.js
=> IAPageNew.js - submit register and login forms on return keypress too

src/js/ia/IAPageNew.js, src/scss/ia/_new.scss, src/templates/description.handlebars, src/templates/src_url.handlebars, templates/instantanswer/new_ia.tx
=> New IA wizard - show error message when id already exists

src/templates/dev_pipeline_detail.handlebars
=> Dev Pipeline - show IAs installed on beta in the detail sidebar to all users

src/js/ia/IAPageNew.js, templates/instantanswer/new_ia.tx
=> New IA wizard - add error message for invalid email address

src/scss/ia/_infobox.scss, templates/instantanswer/ia.tx
=> Typo and overflow fixes

root/static/pages/404.html, templates/footer.tx, templates/header_nav.tx, views/includes/footer.tx, views/includes/header/nav.tx
@MariagraziaAlastra @jbarrett please review. :)
=> Remove some nav and footer elements

src/js/ia/IAPageNew.js, src/scss/ia/_new.scss, templates/instantanswer/new_ia.tx
=> New IA Wizard - show error message if title is empty

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IAPageNew.js, src/scss/ia/_new.scss, templates/instantanswer/new_ia.tx
Fixes the PR modal width issues, adds error messages for when the PR link is empty or incorrect.
Planning to make further improvements (more specific error messages) in another PR.
=> New IA Wizard - fixes and improvements for the PR modal

lib/DDGC/DB/Result/InstantAnswer.pm
=> InstantAnswer.pm - fix typo

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IADevPipeline.js
No need to sort on the backend since we do that on the frontend anyways
=> Dev Pipeline - just sort on the frontend

src/templates/dev_pipeline_detail.handlebars
=> Dev Pipeline - show contributors in the detail sidebar

src/js/ia/IADevPipeline.js
//cc @russellholt 
This makes the hide/make public button refresh after clicking on it
=> Dev Pipeline - update detail sidebar info after field change

src/scss/ia/_new.scss, templates/instantanswer/new_ia.tx
=> Modal Changes

src/js/ia/IADevPipeline.js, src/scss/ia/_pipeline.scss
https://v.usetapes.com/GnIVSCkk4O
=> Sidebar: Initial commit of better sidebar

src/js/ia/IAPage.js
=> Move from jag to ranger

templates/index.tx
Instead of the forum which we don't link from anywhere anymore.
=> Discuss links now point to duckduckhack.com

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IAPageNew.js
=> New IA Wizard - automatically set perl module and tab name for cheatsheets

lib/DDGC/DB/ResultSet/InstantAnswer/Traffic.pm, lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IAPage.js, src/templates/traffic.handlebars
Depends on #1087 
//cc @jdorweiler @jagtalon
=> IA Pages - bring back the frontend for traffic data

src/templates/description.handlebars
=> IA Pages - remove forum link

templates/help/help.tx
=> Sort help articles by sort value in side menu

src/js/ia/IAIndex.js
=> IAIndex.js - fix query filtering

templates/instantanswer/ia.tx
Link to http://docs.duckduckhack.com/welcome/determining-ia-type.html in the next steps if the developer didn't choose an IA type.
=> Add some text that will help choose an IA type.

script/ghIssues.pl
//cc @russellholt 
Changes dev milestone to "complete" if the PR is merged, or to "planning" if it's closed.
=> ghIssues - change dev milestone depending on the PR's status

lib/DDGC/Web/Controller/InstantAnswer.pm, lib/DDGC/Web/Controller/My.pm, src/js/ia/IAPageNew.js, src/scss/ia/_new.scss, templates/instantanswer/new_ia.tx
Just need to store the link in the session when the IA Page is created from a PR and I'm done here.
After login and creation:
=> New IA Wizard - login via GitHub

lib/DDGC/Web/Controller/InstantAnswer.pm
=> InstantAnswer.pm - when a PR is merged, that IA is surely on beta

lib/DDGC/Web/Controller/InstantAnswer.pm, src/scss/ia/_live.scss, src/scss/ia/_pipeline.scss, src/templates/devinfo.handlebars
Return an array of PRs.  WIP, needs more testing.
=> multiple PRs on IA page

templates/instantanswer/new_ia.tx
=> new_ia.tx - all error messages should be red colored

lib/DDGC/Web/Controller/InstantAnswer.pm, src/templates/dev_pipeline_detail.handlebars
=> Dev Pipeline - display IAs with merged PRs as installed on beta

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/Helpers.js
- Issues date can be null sometimes: handle that case
- Add status and date when creating a new row on the Issues table from ia/new_ia
//cc @jdorweiler
=> Fixes on InstantAnswer.pm and Helpers.js

src/js/ia/IAIndex.js, templates/instantanswer/index.tx
=> IA Index - better query matching

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IAPageNew.js
=> Enforce action_token validation on /ia/create

lib/DDGC/Web/Controller/InstantAnswer.pm
Since we retain closed and merged issues as well as PRs now.
=> InstantAnswer.pm - Overview - only add open issues

src/js/ia/IADevPipeline.js, src/js/ia/IAPage.js, src/js/ia/IAPageNew.js
Updating the frontend code accordingly
=> IA Pages - username element in the header changed

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IADevPipeline.js, src/js/ia/IAPage.js, src/js/ia/IAPageCommit.js, templates/instantanswer/commit.tx, templates/instantanswer/dev_pipeline.tx, templates/instantanswer/ia.tx
@jbarrett Let me know if I forgot anything, thanks!
=> IA Pages - enforce action_token validation across all POST endpoints

src/templates/breadcrumbs.handlebars, templates/header_nav.tx, views/includes/header/nav.tx
//cc @russellholt @jagtalon 
Typo fixed, breadcrumbs changed.
Dev Page:
Live Page:
=> IA Pages - minor header fixes

src/scss/ia/_dev-nav.scss, src/scss/ia/_issues-list.scss, src/scss/ia/_loader.scss, src/scss/ia/_pipeline.scss, src/scss/ia/main.scss, templates/instantanswer/dev_pipeline.tx, templates/instantanswer/issues.tx, templates/instantanswer/overview.tx
To reduce the perception that it's loading slowly, Chris and Abe and I thought we should add animations:
https://v.usetapes.com/HrYDIqB086
It reduces the perceived slowness of the page. 
Also:
- Changed border to box-shadow in the sidebars
- Increased opacity in the nav bar
=> Add loading animation to the main DDH pages

src/templates/github.handlebars
=> github.handlebars - repo is one more level up

src/js/ia/IADevPipeline.js, src/js/ia/IAPage.js, src/js/ia/IAPageNew.js
=> IA Pages - strip double quotes from input

src/js/ia/IAPageNew.js
=> IAPageNew.js - no need to check for a min length on login

src/js/ia/IAPage.js, src/templates/commit_page.handlebars
Need to handle the case in which the input is not defined + fixes parent element searching
=> IA Pages - fix editing developer field

src/js/ddgc/ddgc.js, src/scss/content/_global.scss, src/scss/ddgc/_header.scss, src/scss/ddgc/main.scss, views/includes/head.tx, views/includes/header/index.tx
=> 🍔: Initial version of the hamburger navigation

src/js/ddgc/ddgc.js, src/scss/ddgc/_header.scss
- Increase z-index of the close button
- Add back padding-bottom
=> Some fixes on the mobile header:

root/static/css/content.css, src/scss/content/_global.scss, src/scss/content/_notification.scss, src/scss/ddgc/_blog.scss, src/scss/ddgc/_header.scss, views/includes/header/index.tx
- Overflowing content
- Logo needs to be centered
- Font rendering issues
- Mobile landscape needs padding
=> Fixing some implementation issues:

src/js/ia/IAPage.js
Hotfix for staging - editing the developer field was still buggy.
=> IAPage.js - stricter selector for all fields in the live editable page

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IADevPipeline.js, src/js/ia/IAPage.js, src/scss/ia/_live.scss, src/templates/dev_pipeline_detail.handlebars, src/templates/edit_buttons.handlebars
As discussed yesterday //cc @jbarrett
=> IA Pages - remove asana integration

script/ghIssues.pl
Handles multiple example queries in the dax template message.
=> Fix multiple example queries in dax message

src/js/ia/IADevPipeline.js, src/templates/dev_pipeline_detail.handlebars
=> Dev Pipeline - update maintainer

sql/1.145/maintainer_gh.pl
@jdorweiler was having issues updating his data, since he has some usernames from prod, but obviously doesn't have the actual users on his instance's DB, so I made some tweaks to the maintainer script!
//cc @zachthompson
=> maintainer_gh.pl - fix for making it work on dev instances

sql/1.152/maintainer_update.pl
Script to update the maintainer field for live instant answers based on historical data.
=> Update maintainers based on historical information

src/js/ia/IAPage.js
=> fix install on beta button

lib/DDGC/DB/Result/InstantAnswer.pm
=> InstantAnswer.pm - add unsafe to JSON endpoint for all IAs

src/templates/github.handlebars
=> IA Pages - link to maintainer's page in the docs inside a new GitHub issue

sql/1.152/maintainer_update.pl
Remove addition of duck.co user to maintainer field.
=> Only add github user to maintainer

sql/1.152/maintainer_update.pl
Bug in logic, git should be added for all.
Removed the OS IAs maintained by duckduckgo; they should be unmaintained.
=> maintainer bug 

lib/DDGC/Web/Controller/InstantAnswer.pm, src/js/ia/IAPage.js, src/templates/pre_edit_maintainer.handlebars
//cc @zachthompson 
Also fixes a bug with saving empty maintainer values.
=> IA Pages - allow removing values when editing live pages

lib/DDH/UserPage/Gather.pm, views/userpage/index.tx
WIP! 
This should get and append issues and pull requests to contributors data, using the GitHub::Issue table as a source.
=> Userpages - fetch GitHub issues

templates/instantanswer/new_ia.tx
Fixes duckduckgo/zeroclickinfo-goodies#2703.
=> New IA Page: Fix broken link in examples

lib/DDH/UserPage/Generate.pm, views/layouts/main.tx, views/userpage/index.tx
Now the links redirect to the proper pages :)
=> Userpages - don't include js.tx (fixes broken link redirects)

lib/DDH/UserPage/Gather.pm, views/userpage/index.tx
And show them in the template:
=> Userpages - get all IAs maintained by a contributor

src/scss/ia/_live.scss, src/templates/devinfo.handlebars
=> Add space between icons and text.

lib/DDGC/Web/Controller/InstantAnswer.pm, script/ghIssues.pl, src/js/ia/IAPage.js, src/scss/ia/_live.scss, src/templates/edit_dev_milestone.handlebars, src/templates/top_details.handlebars
=> IA Pages - restrict changing dev_milestone to planning, ghosted and deprecated when production_state is online

lib/DDGC/GitHub.pm
=> Use Core team instead of Owners team.  Github made us rename Owners team name

lib/DDGC/Web.pm
=> Only filter if_modified_since once we've established it is populated

lib/DDH/UserPage/Gather.pm
Resolves mixed-case / multiple page creation
=> lc maintainer login

lib/DDH/UserPage/Gather.pm
=> Userpages - separate keys for assigned and opened issues and PRs

lib/DDH/UserPage/Gather.pm
//cc @jagtalon 
Dates:
Counts:
=> Userpages - just show counts for closed issues and PRs + fetch last updated date

lib/DDH/UserPage/Gather.pm
=> Userpages - turn issues and pr arrays into hashes (prevents duplication)

lib/DDH/UserPage/Gather.pm
=> Userpages - gather avatars for all IAs contributors

lib/DDH/UserPage/Gather.pm
=> Gather.pm - can't use usernames as keys

root/static/css/ddgc.css, root/static/css/userpages/UserPage.css, root/static/js/userpages/UserPage.js, views/userpage/index.tx
//cc @jagtalon A little addition to your PR :)
=> Userpages - debug info

script/ghIssues.pl
1. Only run ghIssues with the dax token in production.  You need to provide a token otherwise
2. There is a case where the old dax comment wan't correctly found (line: 487)
=> ghIssues updates

lib/DDGC/Schema/Result/User.pm, lib/DDGC/Schema/ResultSet.pm, lib/DDGC/Schema/ResultSet/User/Blog.pm, lib/DDGC/Web/App/Blog.pm, lib/Dancer2/Plugin/DDGC/Session.pm
Cc: @jkv 
My test plan:
- Paging
- 20 posts per page
- Page count correct
- Posts are in descending chronological order
- All pages start with the post chronologically before the last one on the previous page
- Pages can be filtered by topic
- Page count is correct for topic filtered posts
- Only posts with that topic are shown
- Posts
- Legacy links work, /blog/$uri form
- Correct number of comments shown
- Correct poster, has admin badge
- Teaser shown on front page, full content on blog post page
- Posting (nothing has changed here)
- Edit links work for admins
- Delete links work for admins
- Commenting
- Can comment on posts
- Threading is preserved
This is sub-optimal, but here's a quick way to create posts if you need to...
```sql
INSERT INTO user_blog
values (
DEFAULT, 1,
'title', …
```
=> Nix API usage for blog frontend.

script/ghIssues.pl
Prevents ghosted IA Pages from getting unghosted when a PR is closed
=> ghIssues.pl - check dev_milestone isn't 'ghosted' before updating it

lib/DDGC/Config.pm
This is going out as a patch to 1.161.
=> Hotfix: FindBin is inadequate. Fallback.

root/static/js/userpages/UserPage.js
=> UserPage.js - use login instead of id

PULL_REQUEST_TEMPLATE
Cc: @nilnilnil @jdorweiler @russellholt 
Interested in:
- Is this useful?
- Should it contain more? Or less?
=> Basic PR template to help guide verification process

.travis.yml, lib/DDGC/DB/Result/GitHub/Issue.pm, lib/DDGC/GitHub.pm, lib/DDH/UserPage/Gather.pm, sql/1.166/tags.sql, t/github.t
This should fetch tags for all issues and PR, so they'll be available in the frontend for Contributor Profiles.
=> Contributor Profile - fetch issues tags

root/static/js/userpages/UserPage.js
Removing underscores from "ias_developed_only". If this isn't urgent, I can make more improvements on this branch as well.
Otherwise feel free to merge and deploy and I'll open more PRs.
=> Userpage.js - change format for debug info

t/instant_answer_basics.t
I created some dummy data to test prs_count and issues_count. They should contain the number of prs and issues with 'open' state and exclude closed ones.
=> Add tests for #1353

src/js/ia/DDH.js, src/js/ia/IADevPipeline.js, src/js/ia/IAPage.js, src/templates/commit_page.handlebars, src/templates/dev_pipeline_detail.handlebars, src/templates/devinfo.handlebars, src/templates/pre_edit_developer.handlebars, src/templates/pre_edit_maintainer.handlebars
Maintainer URL updated both in the pipeline sidebar and in the single IA Page.
TODO: contributors.
=> IA Pages and Dev Pipeline - update maintainer and contributors URLs

root/static/css/userpages/UserPage.css, root/static/css/userpages/UserPage.scss
Smaller min-width so that we don't have to horizontally scroll on big screens.
=> Smaller min-width

root/static/js/userpages/UserPage.js
The displayed number of issues and PRs are now accurate.
Before:
After:
=> UserPage.js: Check if an issue is a PR or not

root/static/js/userpages/UserPage.js, root/static/pages/ddh_up_index.html
=> Remove duplicate IAs from the "Issues & PRs" tab

dist.ini
Fixed the copyright URL in `dist.ini` to use HTTPS.
#
Nope.
=> Changed URL to HTTPS

root/static/js/userpages/UserPage.js
Add new comleader to the comleaders array.
When loading his profile, the request sent should include the comleader role.
#
I need to deploy DDH profiles as soon as this is merged.
=> UserPage.js - add new comleader

views/blog/index.tx
Added a link to the blog sidebar for the weekly developer newsletter
#
@jbarrett @zekiel 
No, just a bit of HTML
=> Blog: Added link to developer newsletter

templates/header_accountinfo.tx, views/includes/header/accountinfo.tx
Call the sendReq() function when the profile link is clicked, both from the site and from the blog.
Watch the network tab of the dev tools in the browser to make sure it works.
#
=> Send request on profile link click

src/templates/github.handlebars
=> IA Pages - show 'create issue' button on pages for IAs still not live, too

root/static/js/userpages/UserPage.js
Add the new comleader to the list, so its role gets correctly determined for the request.
You can test by loading the DDH Profile with the network tab of the dev tools open, and see if it sends the right role along with the request.
#
need to deploy after this is merged.
=> DDH Profiles - add new comleader

templates/email/duckpan.tx, templates/email/forgotpw.tx, templates/email/newemail.tx, templates/email/newpw.tx, templates/email/notifications.tx, templates/email/register.tx, templates/email/uservoiceclaim.tx, templates/email/wearemail.tx, templates/i/event_notification_group/email.tx
Render hex code properly in IE.
#167
@moollaza 
No
=> Change 3 letter bgcolor to 6 letter hex

templates/header_nav.tx, views/includes/header/nav.tx
Added a link to the new forum to duck.co header navigation.
cc: @russellholt @MariagraziaAlastra
=> Added link to the forum to the duck.co header

root/static/pages/ddh_up_index.html, templates/footer.tx, templates/header.tx, templates/header_nav.tx, templates/wear404.tx, views/blog/index.tx, views/includes/footer.tx, views/includes/header/index.tx, views/includes/header/nav.tx
In an effort to reduce distractions and consolidate the onboarding experience for new users, I've made changes to the header, footer, and blog navigation including:
- Remove "Help" from the Duck.co navigation
- Point all links to duck.co homepage to duckduckhack.com 
- Update the "Instant Answers" link to point to "Live IAs" rather than the "Overview"
- Add a link to the forum to the footer
- Update "Swag" links to hit the shopify store
cc: @zekiel @russellholt @tagawa @moollaza
=> Programming Mission Onboarding Updates

sql/1.186/topics.pl
Add two new topics, "help" and "libraries", as requested
#
@jdorweiler 
=> sql/1.186/topics.pl - add new topics

sql/1.187/languages.pl
Adding the topics for the next programming languages
#
=> IA Pages - add topics for the next languages

root/static/js/userpages/UserPage.js
=> Change default tab to "Issues & PRs"

lib/DDGC/Web.pm, lib/DDGC/Web/Controller/Campaign/SubmitResponse.pm, lib/DDGC/Web/Controller/Duckpan.pm, lib/DDGC/Web/Controller/Feedback.pm, lib/DDGC/Web/Controller/My.pm, lib/DDGC/Web/Controller/Translate/Po.pm, templates/my/delete.tx, templates/my/forgotpw.tx, templates/my/unsubscribe.tx
MX config for this domain will be removed.
=> Hotfix: Remove last duck.co email addresses from templates / email

lib/DDGC/Util/Script/SubscriberMailer.pm, lib/DDGC/Web/App/Subscriber.pm, views/email/a/1.tx, views/email/a/2.tx, views/email/a/3.tx, views/email/a/4.tx, views/email/a/5.tx, views/email/a/6.tx, views/email/a/7.tx, views/email/a/unsub.tx, views/email/a/v.tx, views/email/a/verify.tx
Update placeholder email content with new markup
Please see templates in views/email/a/
#1426 
@AdamSC1-ddg @MariagraziaAlastra 
N/A
=> Email markup

views/email/a/1.tx, views/email/a/2.tx, views/email/a/3.tx, views/email/a/4.tx, views/email/a/5.tx, views/email/a/6.tx, views/email/a/7.tx, views/email/a/v.tx
=> Updating email markup

lib/DDGC/Util/Script/SubscriberMailer.pm
=> Updating email schedule

views/email/a/1.tx, views/email/a/2.tx, views/email/a/3.tx, views/email/a/4.tx, views/email/a/5.tx, views/email/a/6.tx, views/email/a/7.tx, views/email/a/unsub.tx, views/email/a/v.tx, views/email/a/verify.tx
Updating images in email templates
=> Updating email images

views/email/a/6.tx
Fixing email template images
Fixing email template images
@AdamSC1-ddg
=> Fixing email template images

lib/DDGC.pm
Fix username search
https://ddgc-staging.duckduckgo.com/
#
=> Fix username search

script/ghIssues.pl
Encode spaces in markdown links to fix #1436
=> encode spaces

lib/DDGC/Web/Controller/Ideas.pm
Another forum element to be closed
/ideas/newidea - Form submission fails, no new idea can be created
#1442 #1443 
@tagawa 
no
=> Closing ideas POST endpoint

views/email/a/1.tx, views/email/a/2.tx, views/email/a/3.tx, views/email/a/4.tx, views/email/a/5.tx, views/email/a/6.tx, views/email/a/7.tx, views/email/a/unsub.tx, views/email/a/v.tx, views/email/a/verify.tx
This includes a bunch of cleanup in the emails, and updated verify and unsub templates.
Several images have yet to be updated in core. I expect there are some minor margin issues to solve after that.
@jbarrett 
cc @AdamSC1-ddg
=> Emails Cleanup

views/blog/index.tx
Removed RSS feed link (no longer needed) and donttrack.us link.
None
@jbarrett 
Nope
=> Updating social media links in sidebar

lib/DDGC/Schema/ResultSet/Subscriber.pm, lib/DDGC/Util/Script/SubscriberMailer.pm, lib/DDGC/Web/App/Subscriber.pm, t/subscribers.t, views/email/a/1.tx
Bumping first email up to instant delivery.
TBD
#
=> Email schedule changes

views/email/a/1.tx, views/email/a/2.tx, views/email/a/3.tx, views/email/a/4.tx, views/email/a/5.tx, views/email/a/6.tx, views/email/a/7.tx
=> Remove 600px rule for headerImage - basically disables resizing

templates/head.tx, views/includes/head.tx
Twitter had changed some properties so this update should reflect that. Also includes Open Graph data for Facebook. Note I used the @duckduckgo Twitter handle - happy to change it back to @duckgo if preferred.
@jbarrett 
No
=> Updated social media metadata

views/email/a/4.tx
Updates to text, added new end paragraph, added dax's signature image to signature.
#
=> Text changes

views/email/a/3.tx
Made minor modifications to content, removed ghostery, added additional article, added Dax image to signature.
#
=> Fixes to content

views/email/a/1.tx
Updated the signature to include Dax image signature. Centered main image.
#
=> Update to signature

views/email/a/2.tx
Updates to text, add new paragraphs to bring this in line with blog, added dax image signature.
Should deliver a test batch before email goes live.
#
=> Updates to text and footer

views/email/a/1b.tx
Changed the last paragraph to reflect that this group likely has not installed the extension yet. Added extra CTA
#
=> Modified Last Paragraph

views/email/a/1.tx
=> Add Twitter Footer

views/email/a/3.tx
=> Added Twitter Footer

root/static/pages/ddh_up_index.html, templates/feedback/thanks.tx, views/duckduckgo-documentation/index_content.tx, views/includes/footer.tx
Fixed a few links to point to the new blog (spreadprivacy.com) and duckduckhack.com
#
@jbarrett 
Nope
=> Updated blog and DDH links to latest sites

views/email/a/1.tx
Changed underline to italics for "over-estimate".
Added additional line break before Dax's signature image.
#
=> Visual Tweaks

views/email/a/2.tx
Modified spacing in last 3 paragraphs.
Added a description about what Privacy Badger does.
#
=> Visual Tweak and Description

views/email/a/3.tx
Removed excess "!" and combined last two sentences to provide more clarity on what Privacy Badger does.
#
=> Minor Word Changes

views/email/a/6.tx
=> Text Tweak

share/perldoc/duckpan.html, templates/footer.tx, templates/header_nav.tx, views/includes/header/index.tx, views/includes/header/nav.tx
Changed blog links to point to https://spreadprivacy.com/
#
@jbarrett 
No
=> Fixed blog links

lib/DDGC/Web/Controller/Comment.pm, views/includes/comments.tx
Somehow I didn't push these commits to the previous PR.
No blog forms *when logged in*
#1486 
=> HOTFIX: Missing template elements for blog form

views/blog/index.tx
Update signup form in /blog to post to privay tips list
This form should add you to campaign b on daxmailer
https://github.com/duckduckgo/duckduckgo-publisher/pull/315/files
https://github.com/duckduckgo/DaxMailer/pull/35
@MariagraziaAlastra 
=> Update signup form in /blog to post to privacy tips list

script/ddgc_upload_metadata.sh
Additional checks for metadata JSON uploading
#
@jkv 
No
=> Additional JSON checks

templates/footer.tx, templates/header_nav.tx, templates/index.tx
Updates the home page
@moollaza 
=> Duck.co: Update home page

lib/DDGC/Web/Controller/Duckpan.pm
=> Attribute author of duckpan releases to DDGC

lib/DDGC.pm, lib/DDGC/Asana.pm, lib/DDGC/Config.pm, lib/DDGC/PagerDuty.pm, lib/DDGC/Web/Controller/Feedback.pm
This should add security issues directly to on-call
TBD
#
@jkv 
n
=> Post security issues directly to on-call

root/static/css/content.css
1. Grouped button border radii on outer edge only - no radius on the inner edge.
2. Changed all button border radii to 3px
3. Removed inset shadow on the buttons.
4. Changed button active states to #3a7fb4 with the default state at #4495d4.
5. Changed main page background from #f2f2f2 to #f9f9f9.
#
@jbarrett @chrismorast 
No
=>  Added button improvements 

lib/DDGC/Web/Controller/InstantAnswer.pm
Only admins will now be able to edit IA Pages.
@jkv @moollaza
=> Only grant edit permissions to admins

lib/DDGC/Web/Controller/My.pm, root/static/pages/ddh_up_index.html, t/instant_answer_basics.t
Reverts duckduckgo/community-platform#1532
=> Revert "Remove path"

templates/forum/share_suggestion.tx, templates/header_login.tx, templates/modal_login.tx, templates/my/login.tx, templates/translate/index.tx, views/includes/header/login.tx, views/includes/modal_login.tx
Removing signup links on the Complat. self-merging
@jkv 
=> Remove signup links
