src/ia/js/IAPage.js
src/templates/description.handlebars
src/templates/screens.handlebars

Let's just depend on the metadata instead of adding a period automatically in the description.

IAPage: Don't automatically add periods.

---

src/ia/css/ia.css

IAIndex: Adjusted the arrow position

---

src/ia/css/ia.css
src/templates/screens.handlebars

Here's how it looked:
Here's how it looks now:
What I did is hide the top 4px of the image, and replaced it with a `div` with the same color. Now it looks a little better.

IAPage: Hide the image's red bar, and create one in HTML.

---

src/templates/devinfo.handlebars

puts the source files on separate lines.

add <li> around source listing on ia page

---

script/ddgc_release.sh

This is probably not required, but will hang onto it for a couple of days in case a deployment is needed.

Temporary fix for deploying to view vs prod until setups are synced.

---

lib/DDGC/Web/Controller/Root.pm

This is taken care of by Catalyst.
#446

Manual decoding of the urlencoded parameter is not necessary.

---

templates/instantanswer/index.tx

@jagtalon see my latest comment on #453.
Screen:

IE 8 and IE 9 don't support the placeholder attribute

---

src/ia/js/IAIndex.js
templates/instantanswer/index.tx

String.prototype.trim() is only available in IE 9, I think. Replacing them with `$.trim` fixes the problem.

IAIndex: Fix IE 8 errors.

---

lib/DDGC.pm
lib/DDGC/Web/Controller/My.pm
templates/my/delete.tx

While the robustness of our Prosody "integration" needs to be evaluated (#437), we can provide some fixes for the brokenness right now. This should address:
#363 - Deleted users not completely deleted 
Prosody usernames are made lowercase prior to storing them, so we should select on a lowercase username.
#325 - Don't bump forum posts when comments set to deleted user
Explicitly setting the updated date to equal created prevents this.

Fixing user deletion

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/ia/js/IAPage.js

... If not, show the live version instead.
Overview of the changes: the JSON endpoint for the single page now is composed of two hashes: `live` and `edited` (this last one only if the user has edit permissions or is an admin).
The `live` hash has, of course, the live version for each field, while the `edited` hash has the latest edit for each field, or, in case that field wasn't edited, the live version.
In IAPage.js the response from the JSON endpoint gets memorized in a variable, `ia_data`, and if this variable contains the `edited` hash then it means the user is either admin or has edit permissions, so we set `x` to `ia_data.edited`; otherwise we set it to `ia_data.live`. 
//cc @russellholt @jdorweiler @jagtalon @jbarrett

IA Page - show latest edits if the user has the right permissions

---

src/ia/js/IAPage.js

@jagtalon Turns out it was an issue with trimming the text - some values can have spaces or newlines at the end and aren't recognized as the same topic!
While I was working on this, I fixed other queries as well :)

IA Pages - prevent adding duplicated topics (and queries)

---

src/ia/css/ia.css
src/ia/js/IAPage.js
templates/instantanswer/ia.tx

Default view for logged in users with edit permissions:
After clicking on "live" (notice how name and description values change):

IA Pages - add toggle-view button to switch between live and edited data

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/ia/js/IAPage.js
src/templates/commit_page.handlebars
src/templates/edit_dev_milestone.handlebars
src/templates/pre_edit_dev_milestone.handlebars

The dev milestone value can be edited using a dropdown (the available options are hardcoded in the Handlebars template for now, until we are sure about what they should be), and, since the commit page has been updated as well, the edits to this field can be committed.
//cc @russellholt @jagtalon

IA Pages - add dev milestone row in edit mode if user is an admin

---

cpanfile
lib/DDGC/Config.pm
lib/DDGC/Web/Controller/Admin.pm
lib/DDGC/Web/Controller/Admin/Campaign.pm
lib/DDGC/Web/Controller/Campaign/SubmitResponse.pm
lib/DDGC/Web/Controller/My.pm
templates/admin/campaign/bad_user_response.tx

Wear page:
- Enforce (a very short) minimum answer length.
Admin page:
- Go through login page before dumping non-admins to landing page
- Default campaign = first active campaign when not specified
- Present a textarea for usernames when user not specified

Campaign page changes

---

script/ghIssues.pl

Fixes those unicode characters in the title and body fields.
@MariagraziaAlastra @jbarrett @russellholt

use decode_utf8

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/templates/examples.handlebars
src/templates/in_development.handlebars

Not a big change, really. 
Just making sure that when a user clicks on an example link on the static page he gets the intended IA tab for that query.

IA Pages - add '&ia=[tab name]' to the example links

---

lib/DDGC/Web/Controller/InstantAnswer.pm

add some necessary data to this endpoint to be used in the metadata publishing. it's structured slightly differently than /ia/json in that this one is a hash of ia data by id.
`/ia/repo/goodies/json` entries look like
```
"loan": {
"perl_module": "DDG::Goodie::Loan",
"status": "live",
"name": "Loan",
"example_query": "loan $500000 at 4.5% with 20% down",
"description": "Calculate monthly payment and total interest for conventional mortgage",
"repo": "goodies",
"tab": null,
"id": "loan"
},
```
and an entry from `/ia/repo/fathead/json` looks like
```
"muppet_wiki": {
"perl_module": "DDG::Fathead::MuppetWiki",
"status": null,
"name": "MuppetWiki",
"example_query": "elmo muppets",
"description": "Muppets reference",
"src_id": 10,
"src_options":  {
"skip_abstract_paren": "",
"skip_end": "", …
```

additions to /ia/repo

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/ia/js/IAPage.js
src/templates/description.handlebars
src/templates/topic.handlebars

@russellholt @jagtalon The description will be added alongside with name and id when a new IA page will be created, so we want to show the description not only when the IA is deployed and live, but also during the development process, in the dev page.
In order to accomplish this I had to separate topics and description, which were previously in the same Handlebars template.
I also fixed a little bug in InstantAnswer.pm - not all the IAs have a defined tab name, so it's necessary to check before trying to transform it to lowercase.

IA Pages - show the description in the dev page

---

lib/DDGC/Web/Controller/InstantAnswer.pm

@russellholt This checks if the entered name refers to an actual complat user, and, in the case of producer and designer, if that user is also an admin.
If you want to test, an example of an admin account is TestOne.
Account without special permissions example: TestTwo.

Dev IA Page - check username for producer, designer and developer fields

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/templates/in_development.handlebars

Now that we have the is_pr column inside InstantAnswer::Issues we can distinguish between issues and pull requests, and get the id, title, body and tags of a PR on the JSON endpoint.
It will be used in the dev IA page, inside the "in development" dev milestone, to see if a PR has been opened :)

IA Pages - get pull request on the JSON endpoint

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/ia/js/IAPage.js

As said in the comments for #506. Now the tab name is modified (lowercase + spaces removed) inside IAPage.js, and only if the dev milestone is "live", since in that case we need to use it for the example links (the "&ia=[tab name]" bit).

IA Pages - don't modify the IA tab string if dev milestone !== live

---

lib/DDGC/Web/Controller/Campaign/SubmitResponse.pm

@zekiel This change makes the following changes:
- Increases the char count by 10 for a short flag
- Only adds one flag to the email header
- Lowers the confidence threshold for language flagging slightly (65% -> 62%)

Campaign lang detect changes

---

lib/DDGC/DB/Result/Token/Language.pm

Issue  #162
When locales are published, this acts the same way as if both translations had 100 votes - the latest translation from user who has declared more experience in their profile is the one which is chosen.

Do not delete existing 0-vote translations when inserting new translation

---

src/templates/examples.handlebars

@jagtalon the "&ia=[tab name]" was already there for other queries too, just had to fix a bug with the Handlebars template: inside the loop it needs special syntax to access parent values.

examples.handlebars - fix bug in retrieving the tab for other queries

---

lib/DDGC/Web/Controller/InstantAnswer.pm

@russellholt @jagtalon I don't have the latest metadata yet, but I believe you can see that the list is sorted anyway :)

IA Pages Index - sort topics alphabetically in the topics filtering section

---

lib/DDGC/Web/Controller/InstantAnswer.pm

Before (look at the status): 
After:

IA Pages creation - replace underscore with space for the status field

---

lib/DDGC/Web/Controller/InstantAnswer.pm

`decode_json` fails when it runs into weird utf8 characters.  I think the long term fix is to use a separate updates table `One IA has Many updates` similar to the issues table.  That way we can avoid json all together.  I'm happy to work on that but here is a short term fix if we want it. 
@MariagraziaAlastra @jbarrett @russellholt

from and to json

---

lib/DDGC/DB/Result/Help.pm
lib/DDGC/Web/Controller/Admin/Help.pm
sql/1.012/nullable_help_category.sql
templates/admin/help/index.tx

Set category to '-' to hide a help page. Content remains intact should we want to re-publish it later.
@zekiel thanks!

Allow hiding of redundant help pages

---

script/ddgc_github_contrib_stats.pl

- Fix for syntax error
- Use OAuth token for auth, optionally. Falls back to login credentials prompt.

Fixing github stats script.

---

lib/DDGC/Web/Controller/InstantAnswer.pm

IA Pages - dev pages should have dev pipeline instead of index in the breadcrumbs

---

lib/DDGC/Web/Controller/My/GitHub.pm
templates/i/github_user/repos.tx
templates/my/account.tx

Should, in effect, act as a state token as described here:
http://tools.ietf.org/html/draft-ietf-oauth-v2-20#section-10.12
@zekiel @malbin @nilnilnil Thanks!

Require action token for transactions with github.com

---

Gruntfile.js
src/ia/js/Helpers.js
src/templates/planning.handlebars

We needed a generic Handlebars helpers file: from now on every helper will be defined there.
In this specific case I defined a block helper checking if two values are equal - it makes much easier to check for specific repos and can be used to refactor some other parts as well. I believe in the end having more trivial helpers like this one will save us from unnecessary overheads and ugly hacks, and will boost code performance as well. Now, screenshots!
Fathead shows src options field:
Spice shows API docs:
Other types don't show neither API docs, nor src options:

IA Pages - specific type-only fields (plus new Handlebars helpers file)

---

src/ia/css/ia.css
src/ia/js/Helpers.js
src/ia/js/IAPage.js
src/templates/in_development.handlebars

I think three topics should be more than enough for an IA:
Removing a topic doesn't actually remove the select element, it just empties the first option value and sets that one as selected, and then saves the new list of topics:

Dev Pages - multiple selection for topics

---

src/ia/js/Helpers.js
src/ia/js/IAPage.js
src/templates/examples.handlebars
src/templates/qa.handlebars

@jagtalon @russellholt So now we can have the tab name appended on the dev page example query, too!

IA Pages - Handlebars helper for appending the tab name to the example queries

---

lib/DDGC/DB/Result/Token/Domain.pm
lib/DDGC/DB/ResultSet/Token/Language.pm
lib/DDGC/Web/Controller/Translate.pm
sql/1.014/active_flag_for_domain.sql
templates/i/token_domain/form.tx

- Admin interface for domains has an 'Active' option - set to 'No' to hide this domain in the translation interface.
@zekiel @yegg Thanks.

'Active' flag on domains to remove expired domains from translation interface.

---

lib/DDGC/Web/Controller/Campaign/SubmitResponse.pm

@zekiel Explicitly checks for campaign name since some of our nice users have been submitting automatically.

Close phase 1 submit end point

---

share/docroot_duckpan/duckpan.css
share/perldoc/duckpan.css

Slightly increased the contrast ratios of header text to above 4.5:1 for smaller text and above 3:1 for larger text.
This makes the text pass level AA of the [Web Content Accessiility Guidelines](http://www.w3.org/TR/WCAG20/).

Increased contrast in header text to pass WCAG 2

---

src/ia/js/IAPage.js

@russellholt 
[Screencast for the type change](http://gfycat.com/BruisedOrneryCobra)
[Screencast for producer name change](http://gfycat.com/PeacefulThirdCougar) - here the difference with the live version is that if you change a team name from yours to some other user (or if you remove it), the "assign to me" button is shown again without having to reload.

Dev Page - no need to reload when changing type or team values

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/ia/css/ia.css
src/ia/js/IADevPipeline.js
templates/instantanswer/dev_pipeline.tx

@russellholt @jagtalon if you're an admin you can choose to see all IAs in development of which you're the producer, or the designer, or the developer.
A regular user (doesn't matter if he has permissions or not) can see all the IAs which he's developing. 
The filtering is done via CSS classes, like we do in the IA Pages Index.
[Screencast](http://gfycat.com/ColorfulAnguishedChameleon) - on my instance TestOne, which is an admin, is producer of "Another IA in development", designer of "Test" and developer of none.
Screenshot (checkbox is unchecked, so we display all the IAs in development):

Dev Pipeline - add filters on the dev view

---

lib/DDGC/DB/Result/InstantAnswer.pm
lib/DDGC/Web/Controller/InstantAnswer.pm
sql/1.018/answerbar_fallback_timeout.sql
src/templates/planning.handlebars

@russellholt @bsstoner @tommytommytommy @nilnilnil 
Please let me know if I got this right: the column 'answerbar' is a JSON string which, for now, only contains fallback_timeout, but it can easily contain any other value you might need.
You should be able to set the fallback_value for any Spice not yet live inside the Planning panel of the dev page (screenshots below):
JSON data returned:

IA Pages - add 'answerbar' column to the InstantAnswer table and display the field on the Dev Page

---

lib/DDGC/DB/Result/Topic.pm
lib/DDGC/Web/Controller/InstantAnswer.pm

- `[PkgVersion] no blank line for $VERSION after package DDGC::Web::Controller::InstantAnswer statement on line 1`
- `SQL::Translator::Parser::DBIx::Class::parse(): SQLT attribute 'on_delete' was supplied for relationship 'Topic/instant_answer_topics', which does not appear to be a foreign constraint. If you are sure that SQLT must generate a constraint for this relationship, add 'is_foreign_key_constraint => 1' to the attributes.`

Fix some deployment warnings

---

src/ia/css/ia.css
src/ia/js/IAPage.js
src/templates/metafields.handlebars
templates/instantanswer/ia.tx

@russellholt a 'metafields' Handlebars template is now appended to the dev page before the dev milestone panels. 
Right now it only contains the description, but its purpose is more generally to contain all the meta fields, aka fields which don't necessarily belong to a specific dev milestone, such as tab name and topics.

Dev Page - make description editable

---

src/ia/js/IAPage.js

@russellholt Previously when clicking on the up/down arrows on the input[type="number"] fields the focus event wasn't triggered, so in order to save the value you needed either to change the value using the keyboard or to click on the input and outside (or hit the return button) to save.
Minor change, merging right away.

IAPage.js - trigger focus event on input type number on value change

---

src/ia/css/ia.css
src/templates/name.handlebars

@russellholt looks exactly as before, only that now the value in there is the dev milestone instead of the status

IA Pages - single page - change status to dev milestone

---

templates/blog/sidebar.tx
templates/feedback/thanks.tx
templates/i/user_blog/actions.tx

@zekiel This removes the fb "share" buttons from the bottom of blog posts in the index and individual posts.
https://view.dukgo.com/blog/
Thanks!

Remove blog post share buttons

---

lib/DDGC/Web/Controller/InstantAnswer.pm

late night fix
may not be the best way, but consider this a placeholder
maybe also include ready ? 
we were including metadata in the repo release for in dev IAs that don't have perl modules, causing internal issues that were addressed separately

on /repo return only live

---

lib/DDGC/Web/Controller/InstantAnswer.pm

@russellholt a little modification so we just select live IAs and we don't have to skim through in development ones, as suggested by @jbarrett.
Didn't use the HashRefInflator thing because we have to retrieve columns which need to be decoded from JSON, I think it's fine and fast enough for now anyway

InstantAnswer.pm - select live IAs for the repo JSON endpoint

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/templates/commit_page.handlebars

@russellholt Right now if you remove all topics from a live IA and then go to the commit page it doesn't display anything; this PR fixes that.

IA Pages - allow removing all topics

---

lib/DDGC/Web/Controller/InstantAnswer.pm

@moollaza Fixes the bug about fields not showing for pages with the same name

InstantAnswer.pm - get_edits - use ID instead of name to find the IA

---

lib/DDGC/Web/Controller/InstantAnswer.pm

So the IsAwesome goodies don't show up anymore and we can specify to show IAs without topics as well. Urgent, merging right away

InstantAnswer.pm - use another syntax for the OR in the where clause inside ialist_json

---

src/ia/css/ia.css
src/ia/js/IAPage.js
src/templates/in_development.handlebars
src/templates/planning.handlebars
src/templates/qa.handlebars
src/templates/ready.handlebars

@russellholt previously the content overflowed when setting the type to "fathead"

Dev IA Pages - refresh panels height on autocommit to prevent content from overflowing

---

cpanfile
lib/DDGC/Postman.pm

Generated by [`HTML::FormatText::WithLinks`](https://metacpan.org/pod/HTML::FormatText::WithLinks).
Sample plaintext part for signup email:
```
--14284084110.aE39aF8dA.16636
Date: Tue, 7 Apr 2015 08:06:51 -0400
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
This is an automated email from DuckDuckGo's Community platform. DO
NOT REPLY.
DuckDuckGo
----------
Community Platform
Welcome to the DuckDuckGo Community!
====================================
Thanks for joining duck.co, the DuckDuckGo community changing the
future of search.
Please click the link below to verify this email address:
[1]Yes, I signed up for duck.co with this address
Regards,
The DuckDuckGo Community team.
1. https://view.dukgo.com/my/email_verify/thisisabrandnewaccount/abc123qwe456zxc789abc123qwe4 …
```

Add a plaintext part to HTML mail

---

src/ia/js/IADevPipeline.js

@russellholt 
Previously (notice how Congress and Currency have issues with the "bug" tag, but the other issues are shown as well):
Now (display only relevant issues, hide the ones without the right tag):

Dev Pipeline - only show issues with the right tag when filtering

---

script/ghIssues.pl

This is kinda hard to test since a PR needs to be merged to test it.  I tested it out my flipping some of the data from the github api to make it look like a pr was merged and it worked fine.
I'll explain the idea since it's difficult to test.
1. First go to our db and get all of the issues marked at being a pr
2. build a hash of pull requests.  pull_request_number+repo => { pull request data }
3. Get the current issues for the repo
4. When we get a new issue from the API we delete it from the pr hash.  The idea being that anything that is still live hasn't been merged/closed
5. If there's anything left in the pr hash at the end of checking the current issues then it has either been merged or closed.  Run the merge_files sub
merge_files sub
1. get detailed data on the issue
2. check if it …

add file paths when a pr is merged

---

lib/DDGC/Postman.pm

- text/plain first is what RFC 1521 describes.
- Some HTML capable clients are not rendering HTML part by default with other ordering.

Switch order of plain text / html mail parts

---

lib/DDGC/Web/Controller/My.pm
lib/DDGC/Web/Controller/Root.pm

Instead of using a single 'invalidate_sessions' value, this change will create a token array on each password reset request (either by email or from within account settings).
For 24 hours AFTER each reset request, session tokens are pushed to this array on login. Any existing session token which isn't in this array will be logged out.
Each password reset request resets this array.
If we were using a more transparent session store we could probably iterate over the data and nuke those matching a given user... Something to investigate for later, DBIC or such.

Fix for session invalidation on password reset request

---

.gitignore
Gruntfile.js

Adding a .scss file in `src/ia/css` (this directory could be changed to `src/ia/scss` but we can do that in the future) will now get compiled and minified when we run `grunt`.

Gruntfile.js: Compass now compiles SASS files.

---

lib/DDGC/Web/ControllerBase/Blog.pm

This explicitly disables body encoding, then sets the encoding in the HTTP header.

Fix for double encoding in blog RSS feed.

---

src/ia/css/ia.css
src/ia/js/IAPage.js
src/templates/development_content.handlebars

@russellholt Right now, after saving a field, if you modify it again the highlight (green if the new value was saved, red if not) stays on. It should be removed instead, until a new attempt to save that field is performed.
Also, the checkboxes had weird highlighting, so I fixed that as well.
Checkboxes highlighting before:
Checkboxes highlighting after:

Dev IA Pages - fix the checkboxes highlighting when saved and remove highlight from a field if it's being modified again

---

Gruntfile.js

This will actually make `grunt watch` compile the Handlebars files.

Gruntfile.js: Modifying .handlebars with grunt watch doesn't work.

---

lib/DDGC/Web/Controller/InstantAnswer.pm

@jdorweiler @russellholt Fixes the issue with committing edits for the ID field

InstantAnswer.pm - get meta_id as id in current_ia

---

lib/DDGC/Web/Controller/InstantAnswer.pm

@moollaza @russellholt 
Now unless the the last path part after "pipeline/" is equal to "live" or "deprecated", the pipeline will fall back to the dev view, with all the IAs in development.

InstantAnswer.pm - fallback to default dev pipeline view if the url argument is incorrect

---

lib/DDGC/DB/Result/InstantAnswer.pm
script/ghIssues.pl
sql/1.040/forum_link.sql

This will create a new IA page and automatically try to find the following data
```
id => from the duck.co link
meta_id => from the duck.co link
name => from the duck.co link
status => set to "development"
dev_milestone => set to "development"
description => parsed from comment in PR
created_date => current date
perl_module => from lib/DDG/<repo>/ file if one is found
forum_link => parsed from comment in PR
api_docs => parsed from comment in PR
developer => from github api data
```
I have it set to skip any IA that is already exists so that we don't overwrite any of our current data. 
**To test:** 
`./scripts/ghIssues.pl`
then check the pipeline page.

Automatically create an IA page from a PR

---

script/ddgc_dev_server.psgi
script/ddgc_dev_server.sh

So in my experience the "memory" plack panel isn't of real use (the information isn't immediately helpful and is immediately available elsewhere) and it adds a significant performance penalty. This turns it off.
I also added a `-n` option to ddgc_dev_server.sh to not render the plack panels at all - I understand this can interfere with front end work, so you can now disable it without disabling all debug output.
cc @jagtalon @MariagraziaAlastra @jdorweiler 
Thanks!

Dev server performance tweak / plack panels option

---

lib/DDGC/DB/Result/InstantAnswer.pm
sql/1.041/pr_field.sql

Added dev_milestone to the end point so we can check the status of the IA before trying to run tests on it. 
The pr field seem to be missing too.  

add pr field and dev_milestone to end point

---

src/templates/base_info_content.handlebars

Avoids having a link with no href set.

IA Dev Page - don't make example query a link when test machine is not set

---

script/ddgc_rebuild_dev_db.pl

The database update script fails on the pr field so just skip it.  You can get these from running ghIssues if you really need them.

skip pr field when rebuilding

---

cpanfile
lib/DDGC/DuckPAN.pm

If we really need it, we can generate docs some other way. I suspect we won't.

Lose CPAN::Documentation::HTML dependency

---

lib/DDGC/Web/Controller/Help.pm

This was handled by nginx, but a serious of deprecations in other areas has broken it.
Let's just fix it in the help controller.

Fix legacy help redirect

---

.gitignore
bower.json
package.json
src/scss/ddgc/main.scss
src/scss/ia/_vars.scss
src/scss/ia/main.scss
src/scss/ia/overview.scss

Run `sudo npm install && bower install && grunt` to test. You need to install bower first `sudo npm install -g bower`.
I can't add `bower` to `package.json` because it's a cli program, unfortunately, and needs to be installed globally.

Move to using bower when fetching 3rd-party SCSS.

---

services/ddgc.psgi

Required for reverse proxy awareness and such.

Enable default plack middlewares for DDGC::Web

---

script/ghIssues.pl

If the issue is a PR and there is already an existing IA page for it:
1. get all the usual fields that we're trying to auto create.
2a. If the existing IA page doesn't have anything for that field.  Update it.
2b. If the existing IA page already has data for that field, Skip it
For example, this will cover the cases where someone updates the PR later to do things like add api documentation, add a description if where wasn't already one, or adds a duck.co link.

update IA page if pr changed

---

src/js/ia/IAPage.js

Prevents empty topic values from being included in the JSON string sent to the endpoint.

IAPage.js - use getGroupVals() when adding or changing topic, too

---

src/scss/ia/overview.scss
src/templates/overview.handlebars

Buttons on the overview page were messed up after the latest style changes; now they're fixed.

IA Overview Page - fix btn--primary style

---

Gruntfile.js
lib/DDGC/Web/Controller/InstantAnswer.pm
root/static/css/content.css
src/js/ia/IADeprecated.js
src/js/ia/IADevPipeline.js
src/js/ia/IAIssues.js
src/js/ia/IAOverview.js
src/scss/ia/_dev.scss
src/scss/ia/_ia.scss
src/templates/overview.handlebars
templates/instantanswer/deprecated.tx
templates/instantanswer/dev_pipeline.tx
templates/instantanswer/issues.tx
templates/instantanswer/overview.tx

@russellholt So, now the URLs are:
* Overview page: ia/dev
* Dev Pipeline: ia/dev/pipeline
* Issues: ia/dev/issues
* Deprecated: ia/dev/deprecated
Index and single pages have the same URLs, as usual. I changed the breadcrumbs accordingly.
Still need to add the toggle button on the Overview page and then I'm done.

IA Pages - Overview page should be the starting point: change URLs accordingly

---

README.markdown
lib/DDGC.pm
lib/DDGC/Util/Markup.pm
lib/DDGC/Web/Service/Blog.pm
lib/Dancer2/Plugin/DDGC/Request.pm
lib/Dancer2/Plugin/DDGC/Validate.pm

- Ditch libcurl, HTTPS verification is wonky
- Ditch regex for detecting if image already proxied - not reliable
- Don't filter requests for single posts on company blog / live flags to allow preview
- Add company_blog flag to validator, since its value still exists in db
@malbin If that's not the last of them I'll eat my hat!
(pass the ketchup just in case)

Deployment hot fixes

---

lib/DDGC.pm
src/js/ia/IAIndex.js
templates/instantanswer/index.tx

@russellholt The URLs will be like "/ia?&repo=spice&template=info"; when the page is loaded the final part of the URL path gets splitted and for each field-value pair, if it's valid, a click event is triggered on the corresponding element.
It basically mimics the manual clicks on the filter options in the sidebar.
I just need to change the URL whenever a filter option is clicked, so we easily get a shareable link without the hassle of having to craft it ourselves, and then it's done.

IA Index - add ability to filter using URL params

---

lib/DDGC/DB/Result/Language.pm
lib/DDGC/DB/Result/User/Blog.pm
lib/DDGC/Schema/Result/User/Blog.pm
lib/DDGC/Web/Controller/My/Blog.pm
lib/Dancer2/Plugin/DDGC/Validate.pm
sql/1.051/00-blog-new-cols.sql
templates/my/blog/edit.tx

This allows basic Markdown syntax in blog posts (i.e. if you want highlighted code blocks, you should use HTML for now), using [`Text::Markdown`](https://metacpan.org/pod/Text::Markdown).
@jagtalon @moollaza @russellholt @zekiel

Markdown blog posts

---

lib/DDGC/Web/Service/Blog.pm

coalesce() is a better option than concat() for this type of sort - this fixes sqlite and older postgres support.

Fix blog sorting

---

src/js/ddgc/ddgc.js

@bsstoner @andrey-p Many thanks for you feedback in #779 
I think this should be closer to achieving what we want (filter out duckduckgo and $self, where $self is staging, dev or view - dynamic).
Could you also confirm I am right with my string escaping - I think I need to escape the backslashes themselves when building a new re from strings - this is what my REPL tells me anyway:
```
> /^https?:\/\/(\w+\.)?(duckduckgo\.com|duck\.co)/
/^https?:\/\/(\w+\.)?(duckduckgo\.com|duck\.co)/
> new RegExp("^https?:\\/\\/(\\w+\\.)?(duckduckgo\\.com|duck\\.co)")
/^https?:\/\/(\w+\.)?(duckduckgo\.com|duck\.co)/
```
Thanks!

Perform redirect for hosts that aren't this and ddg

---

views/includes/user/username.tx

Don't know where "nobody" came from - I think it was a mishandled special case which got ported over to new templates.

Change non-private username to "hidden"

---

script/ddgc_leak_report.pl

@nilnilnil @malbin 
This is intended to help track down object instance leaks in a coarse fashion. The idea is you pick a route and do multiple runs against it with different numbers of iterations (GET requests) and compare the numbers:
```
$ script/ddgc_leak_report.pl 1 '/help' 2>&1 | grep -v ^DEP
Tracked objects by class:
DBD::Pg::DefaultValue                    1
DBI::var                                 5
DBIx::Class::Cursor::Cached              1
DBIx::Class::Storage::DBI::Cursor        1
Hash::Merge                              2
$ script/ddgc_leak_report.pl 100 '/help' 2>&1 | grep -v ^DEP
Tracked objects by class:
DBD::Pg::DefaultValue                    1
DBI::var                                 5
DBIx::Class::Cursor::Cached              100
DBIx::Class::Storage::DBI::Cursor …
```

Object instance leak detection

---

lib/DDGC/Base/Web/Common.pm
lib/DDGC/Schema/Result/Comment.pm
lib/DDGC/Schema/Result/User/Blog.pm
lib/Dancer2/Plugin/DDGC/Markup.pm

@nilnilnil @malbin #784 paying off already.
/blog.json appears to be leaking `DDGC::Util::Markup` instances like crazy. This moves the facility out to the application and makes an instance available via a plugin keyword.
```
$ script/ddgc_leak_report.pl 1 '/blog.json' 2>&1 | grep -v ^DEP
Tracked objects by class:
DBD::Pg::DefaultValue                    1
DBI::var                                 5
DDGC::Util::Markup                       38
Hash::Merge                              2
$ script/ddgc_leak_report.pl 100 '/blog.json' 2>&1 | grep -v ^DEP                                                                                                                                 
Tracked objects by class:
DBD::Pg::DefaultValue                    1
DBI::var                                 5 …
```

Fix apparent DDGC::Util::Markup instantiation leak.

---

script/ghIssues.pl

When auto creating IA pages the ID was being changed whenever the name changed.  This caused the duplicated IA pages.  It also caused the problem that @zachthompson saw where he updated the name and it reverted back the next time ghIssues ran. 
To fix this I'm getting the IA page from the DB and only updating `undef` fields.  Any fields from the DB that are already set will remain unchanged. 

dont update any existing data from the db

---

lib/DDGC/Util/Markup.pm

`HTML::TreeBuilder::LibXML::Node::as_XML` doesn't handle empty elements correctly so if, say, some BBCode has empty tags and generates `<b></b>`, `as_XML` will output <b />
`as_HTML` will output the correct opening / closing tags for empty nodes, but will also do the same for tags which don't nest, like `<br>`, `<hr>` and `<img>`, i.e. you'll get `<br></br>`.
Since only `</br>` poses an actual problem in our output, I've filtered these out as a quick fix until other options are explored.

Fix generated HTML content tag closing

---

src/js/ia/IAPage.js

Our image proxy checks if the end of a URL contains .jpg / .gif / .png. Since we don't have that in our URLs (because of the `nocache` parameter), it wasn't serving the images at all.

IAPage.js: Image proxy should have the parameter f=1

---

src/scss/ia/_live.scss
src/templates/github.handlebars

If there are no tags, position the "created" label somewhere else.

github.handlebars: Fend against missing tags.

---

lib/DDGC/Web/Controller/InstantAnswer.pm

@russellholt @jagtalon as requested

InstantAnswer.pm - set test machine to null when changing dev milestone to 'live'

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IADevPipeline.js

@russellholt @jagtalon the check happens when creating a new IA Page and also when editing the meta_id both on the dev pages and the live pages; any non-alphanumeric char gets replaced by an underscore, unless they're at the beginning or end of the string: in that case they get cut off entirely.
The ID can have numbers in it, but they can't be at the beginning of the string, and they need to be mixed with alphabetic (a-z) chars.
If the string only contains weird chars and/or numbers, it gets emptied, so the caller won't save it.
Also, now inside the dialog for creating a new IA Page the ID input field turns red if the entered string is invalid and thus the page is not created.

IA Pages - make sure the ID (and meta_id) doesn't have weird chars in it before saving

---

lib/DDGC/Config.pm

@zekiel I know we plan to rewrite these, but in the mean time using a plural goes a long way to improving consistency between the /wear phases.

Use plural 'friends' in followup question.

---

cpanfile
script/ghIssues.pl

Arg.  @jdorweiler  I figured out why I could not run your ghIssues.pl script on my box -- because I upgraded to Net::GitHub v0.77 which handles utf8 strings differently so you no longer need to decode stuff.
But I need v0.77 because it has methods for new parts of the github api.  So I think we need to release an updated version of your script at the same time I upgrade Net::GitHub.
This pr has the changes.  
cc @MariagraziaAlastra @jbarrett

Upgrade Net::GitHub to v0.77

---

lib/DDGC/Web/Controller/My/GitHub.pm
templates/my/account.tx
templates/my/github/index.tx

This currently does nothing, is getting in the way of other work.

Temporarily disable / hide GitHub account linking.

---

lib/DDGC/DB/Result/Idea.pm
lib/DDGC/Web/Controller/Ideas.pm
templates/ideas/sidebar.tx

- Adds 'Quack and Hack' status.
- Adds ability to link to status by name rather than numeric ID (e.g. /ideas/status/quack-and-hack, /ideas/status/live)
- Can be reverted to "Needs a Developer" status after the event with a single db op

Quack and Hack IA status

---

lib/DDGC/Feedback/Config/Suggest.pm

We capitalize it everywhere in the docs and we should follow suite here too. It also helps to make the term a little more pronounced on the page.
to @jbarrett 
/cc @zekiel

capitalize Instant Answer

---

script/ddgc_release.sh

@malbin @MariagraziaAlastra If pg_dump is running on production, you will see the following:
```
************* W A R N I N G *************
It appears a database backup is in progress
This will BLOCK schema changes from deploying
Continue deployment [y/N]?
```
This will allow you to abandon a deployment if there are schema changes for the current release.

Give option of bailing out of deploy when pg_dump is running.

---

lib/DDGC/DB/ResultSet/GitHub/Comment.pm
lib/DDGC/DB/ResultSet/GitHub/Issue.pm
lib/DDGC/DB/ResultSet/GitHub/Pull.pm
lib/DDGC/DB/ResultSet/GitHub/ReviewComment.pm
lib/DDGC/Stats/GitHub.pm
lib/DDGC/Web/Controller/Admin/Stats.pm
src/scss/ddgc/_github_stats.scss
templates/admin/stats/github.tx

The main goal here is to add the ability to specify a custom date range when looking at community stats.
I got carried away though and changed the look for the stats.

Updated layout for stats.  Added ability to get custom date range.

---

lib/DDGC/Web/Controller/Ideas.pm
src/templates/advanced.handlebars
src/templates/description.handlebars
templates/i/idea/view.tx

@russellholt @jbarrett @zekiel This automatically creates an IA Page from an Idea thread when it's claimed, and it fills in the following fields:
- id, meta_id (aka the editable IA Page id) and forum_link from the idea thread id, 
- the name from the thread title, 
- the description from the content of the first post,
- created_date (using Time::Local),
- dev milestone, setting it to "planning".
Also, the user who claimed the idea gets edit permissions for it.
If the idea is unclaimed and then claimed again, we only update the missing IA Page values without overwriting the existing ones, and give edit permissions to the new claimant.

Create IA Page from Idea thread when a user claims it

---

sql/1.071/01_user_roles.sql

Not doing this will lead to pkey conflicts since there is so much overlap in the sets

Merge idea manager / forum manager data migration clauses

---

lib/DDGC/Util/Script/ActivityMailer.pm

Whatever way we are abusing time zones in the data right now is bonked.
For now, this works.

Set TZ for 'now'

---

lib/DDGC/GitHub.pm

Updating the github_user table causes problems when the user has deleted their account or renamed it.  Need to restructure the code to handle that.  But atm this feature isn't needed.  So I will just comment it out.  This has the added benefit of decreasing the # of requests to GitHub api by like 80%.

Don't update the users table.  Its not needed atm.

---

Gruntfile.js

When first running Grunt, `build/` might not exist so deleteBuildFiles throws an error. This workaround makes sure that there's a build/ directory in the first place before doing anything.

Gruntfile.js: Don't let deleteBuildFiles error out.

---

script/ghIssues.pl

I'm pretty sure this is what was causing the messed up perl modules like `DDG::Sports/MLB/Games`.
I don't have the complat set up so this needs some testing.

fix messed up perl modules from ghIssues

---

lib/DDGC/DB/Result/InstantAnswer.pm
script/ghIssues.pl

cc @jdorweiler @zekiel @nilnilnil 
So it appears that ghIssues (as it runs on view anyway) generates very similar updates for each run - we should probably quash activity generated by these and stick to generating activity based on human activity for now...

Do not generate activity if updates are from ghIssues.pl

---

lib/DDGC/Schema/Result/ActivityFeed.pm
lib/DDGC/Schema/Role/Result/ActivityFeed/AdvancedDescription.pm
views/email/activity.tx
views/includes/activity_feed/instant_answer_updated.tx

So the emails we've recieved so far have been pretty uninformative. "IA Page Created" is OK, but "IA Page Updated" is less useful - what exactly has been updated?
This role allows **optional** advanced rendering for an activity feed entry. If description isn't going to cut it, you can expand on it here with a sub based on your category name and action.
...I am beginning to think that an application that wants to qualify as `$schema->app` should provide an xslate instance since instantiating one for each result (whether needed or not) is pretty crusty and probably slow.
...though not as slow as everything else :wink:

Advanced Activity Rendering

---

lib/DDGC/DB/Base/ResultSet.pm
lib/DDGC/DB/Result/Idea.pm
lib/DDGC/DB/Result/User.pm
lib/DDGC/Schema/Result/User.pm
lib/DDGC/Schema/ResultSet/User/Role.pm
lib/DDGC/Schema/Role/Result/User/Subscription.pm
lib/DDGC/Util/Script/ActivityMailer.pm
lib/DDGC/Web/Controller/Ideas.pm

cc @zekiel @russellholt @MariagraziaAlastra @nilnilnil 
I discussed this with @MariagraziaAlastra already, would be interested in other thoughts.
First thought of mine, doing this without being explicit about it is potentially problematic (especially without a nice way to unsubscribe or remove the subscription).

Subscribe a user to IA Page updates when IA is claimed

---

cpanfile

New versions for Pinto:
```
http://www.cpan.org/authors/id/R/RI/RIBASUSHI/DBIx-Class-0.082820.tar.gz
http://www.cpan.org/authors/id/R/RI/RIBASUSHI/SQL-Abstract-1.81.tar.gz
http://www.cpan.org/authors/id/H/HA/HAARG/Moo-2.000002.tar.gz
http://www.cpan.org/authors/id/H/HA/HAARG/Role-Tiny-2.000001.tar.gz
http://www.cpan.org/authors/id/F/FR/FREW/DBIx-Class-Helpers-2.031000.tar.gz
```

cpanfile - bump DBIx::Class version

---

lib/DDGC/DB/Base/ResultSet.pm

For some reason the DDGC::DB base ResultSet class was written to extend the DBIC components it used rather than use the `load_components` method.
Using `load_components` we no longer get conflicts around `Helper::ResultSet::Shortcut::OrderBy` and `Helper::ResultSet::Shortcut::OrderByMagic`.
Further work may include restricting Shortcut helpers to the set we use but we shouldn't **have to** do this.

Fix C3 Method Resolution errors.

---

lib/DDGC/Web/Controller/Ideas.pm

Index controller route (`sub index`) was causing a warning here.
Should this be an 'eq' check? Or status number?

Disambiguate Core::index call

---

lib/DDGC/Web/Controller/Ideas.pm

@tagawa Just needed to get ideas which are claimed && have an IA Page, instead of claimed ideas with an undef IA Page :)
Now it works:

Ideas.pm - fix claimed page (duck.co/ideas/claimed)

---

src/js/ia/Helpers.js
src/js/ia/IAPage.js
src/templates/advanced.handlebars
src/templates/description.handlebars
src/templates/devinfo.handlebars
src/templates/examples.handlebars
src/templates/top_details.handlebars

Now details use the staged object in order to keep unsaved values when refreshing the Handlebars templates as well, in order to prevent data loss when editing details and committing some other field without first saving.
Also fixed some issues with keeping the unsaved data for example queries.

Dev Page - fix keeping unsaved values for details and examples

---

lib/DDGC/Web/Controller/Ideas.pm

Fixes #923 and #917 
We might want to add more statuses to ignore, e.g. "under review", or maybe create a completely new status, e.g. "complete", for IAs merged but not yet live, like in IA Pages.
It should be sufficient for now though.
@tagawa @jbarrett (I know you're out, just adding you in the loop to let you know)

Ideas Forum - unclaim idea when the status is updated to 'live' or 'declined'

---

src/js/ia/Helpers.js
src/js/ia/IADevPipeline.js
src/scss/ia/_pipeline.scss
src/templates/dev_pipeline.handlebars
templates/instantanswer/dev_pipeline.tx

Last comment is always shown, while last commit is only displayed if the user committed after the last comment was written.
Example: a staff member leaves a comment highlighting a bug in the PR, then the user fixes it, commits the changes and doesn't write a comment afterwards - in that case we show both the last commit and the last comment.
**"Show activity details" is checked**
**These have the last commit**
**"Show activity details" is unchecked**

Dev Pipeline - add activity details for each IA with a PR

---

src/templates/advanced.handlebars

Just forgot an {{else}} in the advanced.handlebars. It's fixed now @mrshu

advanced.handlebars - fix is_fanon value not being displayed correctly

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IADeprecated.js
src/scss/ia/_deprecated.scss
src/scss/ia/_ia.scss
src/scss/ia/_pipeline.scss
src/scss/ia/main.scss
src/templates/dev_pipeline_deprecated.handlebars
src/templates/edit_dev_milestone.handlebars
src/templates/test.handlebars
src/templates/top_details.handlebars
templates/instantanswer/deprecated.tx

I'm introducing a new dev milestone: "ghosted".
Pages with this milestone won't be fetched anywhere , except for inside ia/dev/deprecated, where you will be able to see them if you're an admin - just click on the "Show ghosted pages" checkbox on top. 
This is a temporary solution, since ghosted pages should be on a separate admin page.
TODO: change meta_id when the page is ghosted

IA Pages - add ability to ghost pages

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IAPage.js

Since the meta_id is updated, so there's no need to go check out the Deprecate page to know the new URL.

IA Pages - reload page when dev milestone is changed to 'ghosted'

---

lib/DDGC/Web.pm
lib/DDGC/Web/Controller/Admin.pm
lib/DDGC/Web/Controller/Forum/Admin.pm
lib/DDGC/Web/Controller/My.pm
lib/DDGC/Web/Controller/Root.pm

Setting no-cache in the root route handler (applying it to all requests) causes various annoyances and breakages. Let's stop doing it.

Set Cache-Control more selectively.

---

lib/DDGC/DB/Base/ResultSet.pm
lib/DDGC/DB/ResultSet/InstantAnswer.pm
lib/DDGC/Web.pm
lib/DDGC/Web/Controller/InstantAnswer.pm

I refactored this a little and fleshed it out, since I think it could be generally very useful. Ideally we could use something like [`Plack::Middleware::ConditionalGET`](https://metacpan.org/pod/Plack::Middleware::ConditionalGET) but since that only gets applied after our processing, we wouldn't get a huge time gain (just bandwidth) - processes would still manipulate the data, we just wouldn't send the result. Changes:
- `If-Modified-Since` test and header generation moved out to base controller class
- `->last_modified` moved out to base resultset class (this won't crash if the table has no updated column, but won't be accurate either - apply with care)
- Removing Content-Type etc. headers in 304 response
- Use string equality for if-modified test, since it's basically a tag and not a …

Finishing Last-Modified implimentation

---

lib/DDGC/Web/Controller/InstantAnswer.pm

@MariagraziaAlastra @jdorweiler @mrshu @russellholt 
Seems this is related to returning 304 for the "logged out" version of this JSON after you've logged in. Given this data is dynamic and user-sensitive AND doesn't get slurped in automated tasks I've just removed the header handling for this route.
Steps to reproduce on live currently:
- When logged out...
- Visit an IA Page (Private browser window should re-fetch JSON and set Last-Modified)
- Log in
You should have no 'Edit' controls until you hard-refresh. This change should fix that.

Fixing 'Edit' button issue on IA Pages

---

src/js/ia/Helpers.js
src/js/ia/IADevPipeline.js
src/templates/dev_pipeline.handlebars

- Float the milestone count on the right and get rid of parentheses
- Format the elapsed time differently (e.g. "23d" instead of "23 days", "0d" instead of "today")
- Fix mismatched action options on reload (e.g if type was selected, on reload it's still the first option, but the second dropdown is the milestones one instead of the type one - this change fixes that)

Dev Pipeline - minor cosmetic changes

---

lib/DDGC.pm
lib/DDGC/Config.pm
lib/DDGC/DB/Result/InstantAnswer.pm
lib/DDGC/Schema/Role/Result/ActivityFeed/AdvancedDescription.pm
script/ddgc_dev_server.sh
t/activity_feed.t
views/includes/activity_feed/instant_answer_updated.tx

I meant to push this Friday to start discussing it. Anyway, so far there are a couple of changes here:
- We no longer generate "activity" for every update
- URLs have been "fixed" to use the current host - I found everything being 'duck.co' confusing
Since we don't (that I am aware of) have a ref to the current request there, doing reliable URL stuff from the model is a little funky. This fleshes out the `web_base` config option and adds a wrapper around [`URI`](https://metacpan.org/pod/URI) to generate full URLs for paths and request parameters.
Cc @MariagraziaAlastra

Developer / IA Notification updates.

---

templates/admin/stats/index.tx

updated paths because production currently has an extra "/stats" which causes 404 when clicking things at https://duck.co/admin/stats/

updated paths

---

src/js/ia/IADevPipeline.js
src/scss/ia/_pipeline.scss
src/templates/dev_pipeline_detail.handlebars

If you're an admin, with this change you can edit all the IA fields displayed in the sidebar.
They're saved on return keypress (or on selected option change, for dropdowns), and the Handlebars templates are updated when the sidebar is closed - we fetch again the data from the back-end, so it takes a bunch of seconds to update the view.

Dev Pipeline - edit fields in the sidebar

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/templates/dev_pipeline.handlebars

If the IA's PR has the "priority: high" tag, the IA on the pipeline will get the yellow border on the left:

Dev Pipeline - add .important class to IAs with high priority

---

src/scss/ia/_pipeline.scss

Labels for Fatheads and Longtails should now be correct (it was showing "N" before). 😦 For @MariagraziaAlastra.

_pipeline.scss: "F" and "L" content should be applied to :before element

---

src/scss/ia/_pipeline.scss

The .on-hold class sets opacity to 0.5 which signifies that an IA is, well, on hold.

_pipeline.scss: Add .on-hold class.

---

src/scss/ia/_pipeline.scss

Using `box-shadow` because using `border` takes up space. We don't want no space. 🚀

_pipeline.scss: Add underline under the filter.

---

lib/DDGC/DB/Result/InstantAnswer.pm
src/templates/dev_pipeline_detail.handlebars

Since they can be edited in the actions sidebar, they should be editable in the page sidebar (aka for just one IA) too.
Added producer, template and dev machine.

Dev Pipeline - add editable fields to the page sidebar

---

lib/DDGC.pm

Prepare the hax klaxon.
Our account management is still inadequate (see #437). This closes a more urgent gap.
Unsetting the email verified flag will prevent mail being sent to the "deleted" user.

Stop emailing deleted user accounts.

---

src/templates/dev_pipeline_detail.handlebars

If the IA's PR is high priority, an empty star icon will be shown in the top left corner of the page sidebar.

dev_pipeline_detail.handlebars - add star icon for high priority IAs

---

script/ghIssues.pl

Takes username, admin and comleader roles info.

ghIssues.pl - fetch duck.co user info for last comment and last commit

---

src/js/ia/Helpers.js
src/js/ia/IADevPipeline.js
src/scss/ia/_pipeline.scss
src/templates/dev_pipeline.handlebars
src/templates/dev_pipeline_detail.handlebars

This is just an experiment! I connected the TestOne account to one of the admins accounts on github, so whenever you see an IA with not so much elapsed time compared to the others on top, it means the admin was mentioned in the last PR comment.
Right now the parameters taken into account are:
- Last comment author (higher priority if non-admin)
- Elapsed time since last comment (again, more points if non-admin): the older, the higher the priority
- Elapsed time since last commit if made after last comment or if no comments
- User has been at mentioned in the last comment
- Tags (on hold: -100; high priority: +50)
- Has a PR (any IA with a PR is higher priority than IAs without one)

Dev Pipeline - sort by priority

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IADevPipeline.js
src/templates/dev_pipeline_actions.handlebars
src/templates/dev_pipeline_detail.handlebars

//cc @jdorweiler 
Replaces the dev machine dropdown with an "install on beta" button if the IA is not yet installed / install failed (in this last case it also shows the error message); otherwise shows a link to the IA on the beta server.
Installed:
Not installed:

Dev Pipeline - add beta install status in the single page sidebar

---

script/ghIssues.pl

We need to use the pull request GH api to get the diff comments on a PR.  The issues api only gives us the regular comments.

get all comments for a PR including the diff comments

---

lib/DDGC/Web/Controller/InstantAnswer.pm
templates/instantanswer/topics.tx

//cc @alohaas 
Thanks @jbarrett for the help :)
Page endpoint: ia/topics
JSON endpoint: ia/topics/json
This is what the data looks like:
Additional notes: the js file for this page should be named IATopics.js (or if you want to have another name for it please let me know @alohaas :) )
Also, make sure you login with an admin account before going to ia/topics or you'll be redirected to /ia/, since it's a page meant just for admins.
Thanks!

IA Pages - create new endpoint for the topics page

---

src/scss/ia/_pipeline.scss
src/templates/dev_pipeline_actions.handlebars

Before:
After:
Tested in Safari, Chrome, FF, and IE.

IE is showing some overlapping text.

---

src/js/ia/IAPage.js

//cc @jdorweiler 
Action is 'duckco', not 'duck.co'

IAPage.js - fix typo in the beta data hash

---

src/scss/ia/_pipeline.scss

Fix for type dropdown too wide in the single page sidebar

_pipeline.scss - select elements should have 100% width only in the actions sidebar

---

lib/DDGC/DB/Result/User.pm

@jdorweiler @MariagraziaAlastra My bad, I thought we were just looking for truthiness from this test - didn't consider the result would be assigned for other stuff. This should resolve the useless Result instances finding their way into ghIssues.

Return 1:0, not result instance for $user->is

---

lib/DDGC/DB/ResultSet/InstantAnswer.pm
lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IAIndex.js
templates/instantanswer/index.tx

So following on from #1037, as a stop-gap performance measure this works well enough for now. It will be less feasible as the index grows and some day we will need to fragment loading across multiple requests. Until then...
Here are just the changes required to do the preloading.
@MariagraziaAlastra @russellholt @jagtalon

Preload IA index in template

---

src/js/ia/IAPage.js
src/templates/top_details.handlebars

Bugfix: for the live IA Pages we send a mix of edited and live data, and the edited dev milestone was being used to decide how to render the layout. We should instead use the live dev milestone value.

IA Pages - don't use the edited dev milestone to decide how to render the page

---

.travis.yml

Use travis' caching to greatly reduce build times.  Will cache Perl, metadata, etc., and update the cache when they update.  This branch's build went from 19+ minutes to ~3 using the cache.

Cache deps on travis

---

lib/DDGC/Web.pm

Reading RFCs to design software bad, actually verifying client behaviour good. So we should now be able to use curl...
- First request
```
$ time curl -sD - -z repo.json -o repo.json http://127.0.0.1:5004/ia/repo/all/json
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Last-Modified: Tue, 22 Sep 2015 18:02:58 GMT
X-Catalyst: 5.90085
Content-Length: 501523
Set-Cookie: ddgc_session=579a355f9ccdab96381e3bbd8f4f68fa8dfeb70f; path=/; expires=Fri, 13-Nov-2015 14:28:36 GMT; HttpOnly
Date: Fri, 13 Nov 2015 08:28:36 GMT
Connection: keep-alive
real    0m1.682s
user    0m0.000s
sys     0m0.016s
```
Thanks for the useful and tasty cookie!
- Second request
```
$ time curl -sD - -z repo.json -o repo.json http://127.0.0.1:5004/ia/repo/all/json
HTTP/1.1 304 Not Modified
Content-Type: …
```

Have If-Modified-Since check do date comparison.

---

lib/DDGC/Web/Controller/InstantAnswer.pm
sql/1.101/ddg-attribution.sql

Change ddg attribution name from "DDG Team" to "DuckDuckGo".  The sql only fixes IAs where the only dev is DDG Team.  There are a few with multiple devs that I'll have to fix by hand.  I need to wait for the  change to InstantAnswer.pm for that though.

change ddg attribution name

---

Gruntfile.js

There are concat tasks common between release and local builds. This prevents that repetition.

Gruntfile.js: Cleanup

---

src/js/ia/IADevPipeline.js

Sometimes the install status can have more words than just "success", so we need to use a regex.

IADevPipeline.js - match 'success' in the beta install status using a regex

---

src/js/ia/IADevPipeline.js

Bugfix - previously deselecting one IA without holding shift closed the actions sidebar.

IADevPipeline.js - always open actions sidebar when selected IAs > 1

---

templates/i/help/form.tx

@tagawa Just throwing 99 into sorting by default - can always be changed later.

Give sort a default value - absence commonly throwing exceptions

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IAOverview.js
src/scss/ia/_ia.scss
src/scss/ia/_overview.scss
templates/instantanswer/overview.tx

//cc @jdorweiler  Also set up a basic JSON endpoint for saving (doesn't really do anything for now).
The button is in ia/dev:
The modal for page creation from PR:
On error:
While I was at it I also improved a bit the appearance of the other modal:

IA Overview Page - create IA Page from PR link (front-end)

---

src/templates/examples.handlebars

Fixes failed editing attempts on example queries

IA Pages - don't show examples as editable if dev_milestone is live

---

lib/DDGC/DB/Result/ReleaseVersion.pm
lib/DDGC/DuckPAN.pm
sql/1.102/relver-fkey.sql

The instant_answer.id column doesn't get updated, making it more suitable for the foreign key on release_version.

Change foreign key on release_version

---

Gruntfile.js
package.json

So, I added a gitrm task that takes care of removing all the old release files, a gitadd task that adds the newly released files, and an exec:commit_static task that commits all the new release files, plus package.json.
Can't use gitcommit anymore because it doesn't see deleted files.

Gruntfile.js - add task for removing old static release files

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IADevPipeline.js
src/templates/dev_pipeline.handlebars
src/templates/dev_pipeline_detail.handlebars
src/templates/devinfo.handlebars

Made some changes to the Dev Pipeline and single IA Pages, so that they keep working as they are now.
And also, now closed PRs will be visible on the single IA Page even after the dev milestone is set to "live".
//cc @jdorweiler

IA Pages - update frontend to work with the latest ghIssues script changes

---

lib/DDGC/Web/Controller/Feedback.pm

Since I noticed a drop in feedback and we are getting reports of breakage, I am removing the CSRF check from feedback.
We can consider an alternative approach to this.

Removing CSRF mitigation from feedback

---

lib/DDGC/DB/Result/User.pm

Some stuff (notable dev database deploy) still uses `admin` as an accessor. This change allows stuff like `$user->admin(1)` to continue to work.

Make ->admin act like an accessor

---

script/ghIssues.pl

I'm using the [is_merged method from Net::GitHub::V3](https://metacpan.org/pod/Net::GitHub::V3::PullRequests#is_merged).
Dev Pipeline screenshot (the purple icon is for merged PRs, while the red icon is for closed ones):

ghIssues.pl - merged PRs should have the 'merged' status

---

src/js/ia/Helpers.js
src/templates/examples.handlebars

Fixes not showing example queries as links if they're on beta
//cc @jdorweiler

IA Dev Pages - link to the beta server in the example queries

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/templates/dev_pipeline_stats.handlebars

@jagtalon Done.
So, now when you go to ia/dev/deprecated you get redirected to the login form if you're not admin.
I'm also hiding the link to the page for regular users in the pipeline. I can hide it for the other pages you're putting the blue band header on after you merge your PR, or I can push to your branch if you want.

Dev Center - hide archive

---

src/templates/dev_pipeline_detail.handlebars
src/templates/devinfo.handlebars

Since the beta_install value, when the install is successful, can also be a string containing "success" plus other words.

Dev Pipeline and Dev IA Pages - update handlebars templates to use the match helper

---

script/ghIssues.pl

We're getting issues for anything that has recently been updated.   This means we no longer need to check and update the file list for every PR.
Cuts the number of api requests down by a lot.  If you want to see api requests add this env variable before running. `export NG_DEBUG=1`

only check and update file list for recently updated PRs

---

script/ghIssues.pl

Post some of the data from the IA page back to the PR in a dax comment. 
This runs with ghIssues so data from the IA page would be synced every time it runs.  I have it set to only post to the first comment (excluding dax welcome message).  This means it won't post a comment if someone else comments before ghIssues runs.  So dax gets the first comment or doesn't post. 
@russellholt @MariagraziaAlastra

Post IA data in dax comment

---

script/ddgc_upload_metadata.sh

Because I can't be trusted to tell you what's new, let's make the "force upload" option also re-fetch the data.
This is probably useful as an option to run on the shell when things don't look right on release.
Cc: @bsstoner @russellholt

Have ddgc_upload_metadata's force upload option also force re-get

---

lib/DDGC/DB/Result/InstantAnswer.pm
lib/DDGC/DB/Result/InstantAnswer/Blockgroup.pm
lib/DDGC/DB/Result/InstantAnswer/Issues.pm
lib/DDGC/DB/Result/InstantAnswer/LastUpdated.pm
lib/DDGC/DB/Result/InstantAnswer/Topics.pm
lib/DDGC/DB/Result/InstantAnswer/Users.pm
lib/DDGC/DB/ResultSet/InstantAnswer/LastUpdated.pm
lib/DDGC/Web/Controller/InstantAnswer.pm
sql/1.110/instant_answer_last_updated.sql

- Before any updates:
```
$ curl -I http://localhost:5002/ia/repo/all/json 2>&1 | grep Last
Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT
```
- After updating dev milestone of an IA to deprecated:
```
$ curl -I http://localhost:5002/ia/repo/all/json 2>&1 | grep Last
Last-Modified: Tue, 15 Dec 2015 16:34:25 GMT
```
- After updating the topics of an IA
```
$ curl -I http://localhost:5002/ia/repo/all/json 2>&1 | grep Last
Last-Modified: Tue, 15 Dec 2015 16:35:21 GMT
```
- After updating the description of an IA
```
$ curl -I http://localhost:5002/ia/repo/all/json 2>&1 | grep Last
Last-Modified: Tue, 15 Dec 2015 16:36:26 GMT
```
@jkv Do these cover the failure conditions we discovered?

Track IA updated timestamp for IA table and its relationships

---

src/js/ia/Helpers.js
src/templates/dev_pipeline.handlebars
src/templates/issues.handlebars
src/templates/overview.handlebars

Two things that's faulty with the `timeago` helper:
1. `.replace` method should be a regex in the first parameter and not a string.
2. We can't have implicit variables in the handlebars helpers. ~~Perl idioms seem to have seeped into our JavaScript! `0` isn't the same as `false`. `0 ? 1 : 2` will always result to `2`.~~
Please review, @MariagraziaAlastra.

Helpers: Fix faulty timeago helper.

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IAPageNew.js

Multiple queries can be added using commas to separate them.
E.g. "query1, query2, query3" (doesn't matter whether you put spaces between commas or not)
Also making sure the example queries are saved on IA creation.
//cc @russellholt @jagtalon

New IA wizard - add support for multiple queries

---

src/templates/devinfo.handlebars

Next steps are for IAs in development, on live IAs they're out of place.
Also they were being shown to anyone for any IA, while we only want the author and mantainers of an IA to see the infobox, so we need to check the permissions.
//cc @russellholt @jagtalon

IA Pages - show next steps only for in dev IAs and only to users with permissions

---

src/js/ia/IAPageNew.js

Minor fix - remove any empty examples before splitting the string into an array.

IAPageNew.js - don't include empty examples in the array

---

src/scss/ia/_issues-list.scss
src/templates/issues.handlebars
src/templates/overview.handlebars

//cc @jagtalon 
Since right now we don't have the "grouped by IA" view it makes more sense to sort the issues in the Live Issues page by creation date rather than by IA name.

issues.handlebars - sort by issue creation date rather than alphabetically

---

src/templates/overview.handlebars

//cc @zekiel @jagtalon Link changed, as requested

overview.handlebars - 'learn how to contribute' should link to the docs

---

lib/DDGC/Web/Controller/InstantAnswer.pm
script/ghIssues.pl
sql/1.118/fix-date.sql

Move IA pages to development when we see the IA page link in a PR. 
Fix date bug. Localtime months start at 0 
@jbarrett

move to development and fix date

---

script/ghIssues.pl

Some background:
github considers the automated updates to these comments as activity on the PR
https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2007#issuecomment-168799091
Which is messing up our activity dates on the pipeline page since a dax comment update shows as activity.
To fix:
Only post updates if there has been a change in the IA page data.

only update template messages if IA page data has changed

---

lib/DDGC/Config.pm
templates/view_disclaimer.tx

Detecting we are on staging will start working again!
This is currently a minor issue since we are trying to load development livereload.js stuff on staging.
Need a better solution for this function longer term.

Change old view hostnames to new staging server name.

---

templates/instantanswer/new_ia.tx

Closing tag
Open all the doors and let you out into the world
Closing tag
Turn the lights up over every boy and every girl.
Closing tag
One last call for alcohol so finish your whiskey or beer.
Closing tag
You don't have to go home but you can't stay here.

Wrong closing tag: Messes up the spacing

---

src/scss/ia/_pipeline.scss
src/templates/dev_pipeline_detail.handlebars

//cc @jagtalon 
This shows comments even after the PR is closed or merged. 
I thought I'd use the .no-pr class for the PR link in that case:

Dev Pipeline - always show PR info and comments in the detail sidebar

---

lib/DDGC/Web/Controller/InstantAnswer.pm
lib/DDGC/Web/Controller/My.pm

To be clear, this means every new IA Page (unless it's created from a PR) will be automatically hidden, and it will need to be toggled visible by an admin  - or just wait for the PR to be linked to it.
//cc @russellholt

New IA Wizard - hide new IA Pages even when the author has a verified account

---

lib/DDGC/DB/ResultSet/InstantAnswer.pm
src/js/ia/IAIndex.js

//cc @russellholt 
This allows to sort the index using either sort_asc (for sorting in ascending order) or sort_desc (descending) for any field we retrieve, including live_date and created_date.
Eg if you want to sort in a descending order by live_date: /ia?sort_desc=live_date
If you want to sort as done above and filter by repo, showing only spices:
/ia?repo=spice&sort_desc=live_date

IA Index - add sorting via URL params

---

src/templates/advanced.handlebars
src/templates/pre_edit_template.handlebars

On the live editable page is not shown at all (there's no point in showing it if it can't be edited)
On the dev pages it's shown but disabled (can't remove it without reorganizing the whole details section layout).
Fathead:

IA Pages - disable editing on the template field for fatheads and longtails

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IAPageNew.js
templates/instantanswer/new_ia.tx

When creating an IA Page from a PR link:
When manually filling in the fields:

New IA Wizard - better error message when IA Page already exists

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/templates/devinfo.handlebars

When creating an IA from a PR link the status isn't set and thus it's initially null, and in the IA Page the PR link has the strikethrough, because the status isn't "open".
This PR handles the case in which PR status is null (just show the PR as open) and stores the status when creating an IA Page.
Also, beautifies the IA name (eg if the meta_id is "example_cheat_sheet" the name will be "Example Cheat Sheet").

IA Pages - handle null PR status and New IA Wizard improvements

---

lib/DDGC/Web/Controller/My.pm

The history of this is:
- Emails can be used to reset account passwords
- If you are logged in you know your password, so we require it to change email address
- This prevents someone leaving their computer logged in and having email address reset
Now we support account creation via Github and will import the public email address where it available. However, if no email address is public, we can't do that. In the scenario where a user wishes to set their XMPP password, they'll need an email address set. If you created the account with Github without a public email address, you don't have a password with which to reset the address. (I hope this is clear).
This change along with #1206 should accommodate this by not requiring passwords of Github authed users in order to set email address. …

Fix logic error in Github check while verifying creds on email reset

---

script/ghIssues.pl

Update IA page developer list when a PR is merged.
For testing: 
Run ghIssues.  Check github for any PR that has been merged in the last day.  You should see that developer included in the list on the IA page.

Update IA page developer list when a PR is merged

---

script/ghIssues.pl

When adding a user to the IA Page contributors list, give him edit permissions as well (if his github account is connected to a duck.co account).

ghIssues - give edit permissions to developers

---

src/js/ia/IAPage.js
src/templates/traffic.handlebars

- Fill the traffic data for missing days with zeroes
- Start from live_date instead of 30 days ago, if the IA has been deployed recently (and indicate the correct number of days in the Traffic header in that case)
- Show "not enough data" message when we don't have the data/the IA didn't trigger in the last 30 days
I need to deploy to staging to test this (I don't have the traffic data in my instance). 
In the meantime, this is how it looks when there's no data:

IA Pages - more accurate graphs

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IAPage.js
src/templates/traffic.handlebars

Since we're filling with zeroes the days for which we don't have any traffic data, it's important to make sure that the last day shown is the last time the data was updated.

IA Pages - last traffic date should be equivalent to the last time the data was updated

---

views/includes/head.tx

Since the header is not made to be responsive at the moment, unsetting the initial-scale would show the "zoomed out" view which prevents breakage.

views/includes/head.tx: Don't set initial scale to 1.

---

lib/DDGC/DB/ResultSet/InstantAnswer/LastUpdated.pm

If lots of updates are occurring at once, the potential for the token in instant_answer_last_updated to be updated between your process selecting and updating it exists. This will cause an exception and your process will bail.
If the table has been updated in this time, we don't really need to update it since we don't need (or have) sub-second resolution in this time stamp.
This change wraps the row update in an eval - we don't care about the result of this operation in the case where this fatal race condition occurs.

Work around race condition in IA last updated tracker

---

sql/1.126/rm-fat-long-block.sql

Fatheads and Longtails don't need to be loaded into blocks:
1. Set all fathead/longtail blockgroups to null in instant_answer
2. Remove the option to select those blockgroups
@jdorweiler

Remove fatheads/longtails from blockgroup data

---

script/ghIssues.pl

ghIssues used to assign the "Answer" tab to all goodies, but for Cheat Sheets it should be "Cheat Sheet" instead.
Also fixed giving edit permissions to developers.

ghIssues.pl - fix Cheat Sheets tab name and edit permissions

---

src/js/ia/IAPage.js

- Don't save the edit if both the edit and the live value OR both the edit and the staged edit (when available) are empty;
- Better live/staged values comparison for the developer field;
- Fix saving other_queries (using a strict selector)

IA Pages - fixes for the live editable page

---

src/js/ia/IAPage.js

Deprecated IAs can have traffic data, so we need to check dev milestone as well.

IAPage.js - check dev milestone before attempting to show traffic data

---

lib/DDGC/Web/Controller/InstantAnswer.pm

Seems like ghosted IAs can be on beta as well, so we need to check in order to avoid including them in the Overview page.

InstantAnswer.pm - don't include ghosted IAs in the overview JSON

---

lib/DDGC/Web/Controller/InstantAnswer.pm

If a user has edit permissions for an IA Page it means he's a contributor.
There's no need to check if he's actually listed as such.

InstantAnswer.pm - only check edit permissions for traffic graph

---

lib/DDGC/Web/Controller/Root.pm

Short circuiting all requests to the REDIRECT maker. Using this approach so we can quickly back out the change, should we choose to. Could also do this in nginx, but this is probably easier to back out.

Redirect all requests for /wear to ddg about page

---

script/ddgc_deploy_dev.pl

So, previously it assumed that either the `dropdb` command wouldn't be available or the user running the script would have `dropdb`/`createdb` permissions using peer/trust authentication on the local install of postgres.
That's not the case for me, so if it fails to execute the `dropdb` (for example due to: `dropdb: could not connect to database template1: FATAL:  Peer authentication failed for user "ddgc"` then it will now flip over to the DBI connection.
Additionally, if the db didn't exist then the DBI path would fail, the drop is now defensive

Migrations: The  DB can't be created unless the local user has peer/trust auth with Postgres

---

src/templates/github.handlebars

If the maintainer is a github user or a duckco user with a github account linked, he will be mentioned on any GitHub issue created using the button inside the IA Page.

github.handlebars - mention maintainer in new issues

---

bin/dev_server.psgi
bin/dev_server.sh
bin/generate.pl
lib/DDH/UserPage/Gather.pm
lib/DDH/UserPage/Gather/Github.pm
lib/DDH/UserPage/Generate.pm
lib/Plack/App/Directory/WithIndex.pm
root/static/css/index.css
views/includes/header/index.tx
views/userpage/index.tx

This is almost the same as the original project - `bin/generate.pl` creates pages. `bin/dev_server.pl` is a static file server.
Differences:
- Gather has a db handle via a `DDGC`instance (so we can probably lose the HTTP operations).
- dev_server mounts static files (CSS etc)
- userpage/index is rendered within a duck.co style frame with nav bar and no account info.
Cc: @abeyang @jagtalon

Porting DDH::UserPage to community-platform

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/templates/commit_page.handlebars
src/templates/dev_pipeline_detail.handlebars
src/templates/devinfo.handlebars
src/templates/edit_maintainer.handlebars
src/templates/pre_edit_maintainer.handlebars

//cc @zachthompson 
Live IA Page:
Dev IA Page + duck.co account:
Dev Pipeline detail sidebar:

IA Pages - get rid of duck.co usernames for maintainers

---

src/js/ia/IAPage.js

It works now (screenshot of the commit page JSON endpoint):

IA Pages - fix editing maintainer when live value is null

---

script/ddgc_populate_ia_dev.pl

Pulling maintainer hash from data before insert.
Still barfs a load of "uninitialized value in concatenation" errors from this [stringification override](https://github.com/duckduckgo/community-platform/blob/9d0f94d5ace1219b87ae784ef00bc603a9859395/lib/DDGC/DB/Base/Result.pm#L278-L281) but I'm not too worried about that for now.

Fix ddgc_populate_ia_dev

---

src/js/ia/IAPage.js
src/js/ia/IAPageNew.js

Truncate to the last period, if that's available; otherwise, truncate at 1000 chars length.
In order to test this, I copypasted the text from the [lorem ipsum IA](https://duckduckgo.com/?q=10+paragraphs+of+lorem+ipsum&ia=answer&iax=1) in the description field. 
Newly created IA Page:
Live Page in edit mode:

IA Pages - limit length for the description text

---

lib/DDGC/Web/Controller/InstantAnswer.pm

On the frontend, when looping over the data, we add zeroes whenever we see date gaps to fill.
It seems like we don't always get the data sorted by date though, so we need to user order_by when querying the DB to make sure we don't add zeroes where there's no need for them.

InstantAnswer.pm - sort traffic data by date

---

script/ghIssues.pl

This fixes a bug in the merge_files function.  The way it works right now is actually overwriting the links to the files with whatever files were altered in the last PR.  This is fine for a new IA PR or a PR that alters all the files but in cases where a PR changes only a few files, we loose the others.   
I've updated it do do the following:
1. get the current file list from the database
2. add any new files from the PR
3. remove any files removed by the PR
4. update the database with the new list. 
To test:
1. run `./find_files.pl`.  This takes a good 5 minuets or so to run but should get you upto date file data
2. `psql -U ddgc -f files.sql`.  Update your files in the DB
3. Change this line to get the last 100 hours of issues
https://github.com/duckduckgo/community-platform/blob/f2b0b57 …

Missing files from ghIssues

---

src/js/ia/IAIndex.js

We're using a regexp with a //g flag and running it on multiple strings. Since that regexp maintains state on subsequent calls (lastIndex), we run into matching problems. The solution is to just not use the g flag.

IAIndex.js: Remove //g flag from regexp.

---

src/js/ia/Helpers.js
src/templates/dev_pipeline_detail.handlebars

On production the dates in the detail sidebar all show a negative number.
Turns out the timeago helper got passed an unneeded argument, since these dates come from GitHub and not from the beta server.

Dev Pipeline - fix dates in comments

---

script/ghIssues.pl
sql/1.164/add_devs.pl

Checking for a non null / non empty value for the developer was likely preventing new devs from being added unless the field was filled with developers already.
Thanks!

ghIssues.pl - fix adding new developers when developer value is null

---

lib/DDGC/Web/Controller/Admin.pm
t/image_upload_basics.t
templates/admin/index.tx
templates/admin/upload.tx

Cc: @tagawa 
Review notes:
- Image upload link should be available from admin index (/admin)
- Only admins can upload
- Only image files can be uploaded
- I renamed some random text file to have a jpg extension to verify this
- This is only loosely related to this PR - this feature was implemented separately aeons ago.

Image upload for admins

---

lib/DDGC/Schema/Result/Comment.pm
lib/DDGC/Web/App/Blog.pm
t/blog.t

This change restores the post title to the `<title>` tag of blog posts. It also demonstrates a method for verifying an element of a HTML page using [HTML::TreeBuilder::LibXML](https://metacpan.org/pod/HTML::TreeBuilder::LibXML). It also attempts to demonstrate usage of the proposed pull request template.
The title of the blog post should be shown in the tab / browser window title when viewing a single blog post.
Run tests with:
`$ prove -Ilib t/blog.t`
#1325 - Blog posts missing title
#1334 - Basic PR template to help guide verification process 
@nilnilnil is probably getting bored of these
No.

Fix blog title on post pages

---

lib/DDGC/DB/ResultSet/InstantAnswer/Traffic.pm
lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IAPage.js

The previous dbix query wasn't exactly getting us the right data for the pixel graphs.  It also needed an awkward `get_array_by_pixel` helper function.  So why not just do it all in the sql query, right?
I also update the date calculation to get us 30 days instead of the 28 days we're getting right now. 
Some before and after examples:
https://duck.co/ia/view/latex
Before
After
https://duck.co/ia/view/airlines
Before
After

fix traffic graph

---

lib/DDH/UserPage/Gather.pm

Fixes linking to the wrong IA in the assigned and opened PRs section.
//cc @jdorweiler 
To test this just grab the latest github data and check the IAs linked to PRs in userpages are the correct ones.

Userpages - check the issue repo too to avoid colliding issue numbers

---

lib/DDGC/Web/Controller/InstantAnswer.pm
t/instant_answer_basics.t
t/lib/DDGC/TestUtils.pm

Cc: @MariagraziaAlastra @russellholt 
Here is a very basic IA flow (create a new IA, verify it exists in database) which should demonstrate:
- DB schema rollout
- Plack test app creation (with testutils session integration)
- How to create and get a session for a user of a given class.
- How to test things with CSRF mitigation.
- The most basic of [Test::More](https://metacpan.org/pod/Test::More) assertions (read this doc).
Thanks to @MariagraziaAlastra for help navigating the instant_answer controller.

Basic IA controller tests

---

.travis.yml
Gruntfile.js
bower.json
cpanfile
package.json
script/ddgc_deploy_test_db.pl
src/t/config.json
src/t/ia/index.js
src/t/run.bash
src/t/run.sh
src/t/sql/ia.sql

//cc @nilnilnil 
This is still very very WIP, I just started with a little demo of what we can do with casperjs.
TODO: add some modules with utility functions we can reuse, add grunt task.
**How to install casperjs on your instance:**
- `npm install` This will install phantomjs - I had to pin it to 1.9.8 because that's the latest release working seamlessly with casperjs
- `bower install` this will install casperjs, since it's available as a bower module.
- `export PATH=$PATH:node_modules/phantomjs/lib/phantom/bin`
**How to run a test:**
`casperjs test [filename] --hostname=[hostname]`
For example, in my case:  `casperjs test src/t/ia/index.js --hostname=maria`.
When we'll have the grunt task it should be even easier, though.
Thanks @jbarrett for the help!

Add frontend integration tests 

---

lib/DDH/UserPage/Gather.pm

//cc @jagtalon 
Currently, they include closed/merged issues and prs as well, but we only want to know how many are open.

Gather.pm - count_prs and count_issues should only include open ones

---

script/ddgc_generate_traffic.pl

`script/ddgc_generate_traffic.pl` generates random traffic data for local testing.
Fixes #1303 
/cc @jdorweiler @MariagraziaAlastra @jbarrett

Add script for random traffic data generation

---

lib/DDGC/Web/Controller/InstantAnswer.pm
t/instant_answer_basics.t

Creating a new IA (both from scratch and from a PR link) is broken on the live site.
Problem was a typo (a second "my" which made it look like the variable was different from the one defined previously for the maintainer).
While I was at it I also fixed a bug with contributor names when the author type is "github" (previously used the duck.co username, now it uses the github login)
If you want to test this manually, log in as a user with a github account connected and try creating an IA from ia/new_ia.
Expected: the page is created and you're set as maintainer and added as contributor, both using your github account.
Nope
@tagawa, who spotted the bug!
I need to deploy this as hotfix now and then it'll be included in the next regular deployment as well.
- Mobile …

InstantAnswer.pm - fix create_ia (called from the new IA wizard page)

---

root/static/js/userpages/UserPage.js

They weren't being shown on the page before.
`#2754` is now being shown. Here was the original bug report:

UserPage.js: Add PRs that were created by the user

---

lib/DDGC/Web/Controller/Root.pm
templates/notice_campaign.tx

Sends requests to duckduckgo.com when the banner is shown and when it's clicked.
You just need to watch the network tab in the developer tools to see the request,
provided you logged in using an account with a GitHub user linked.
#1378 
@jbarrett @jagtalon @russellholt 

Banner - send req on show

---

lib/DDGC/DB/Result/User.pm
lib/DDGC/Web/Controller/My.pm
templates/notice_campaign.tx

When you click the 'x' in the DDH Profile notification, this will dismiss it and prevent it showing again.
- You will need Github oauth set up.
- Generate user pages from synced IA data (if you have not already)
- Log into your dev instance as a user with a DDH Profile via Github.
- You should see a banner notification linking to your profile, with the anchor '#tutorial', on all community platform pages, apart from /blog
- Clicking the 'x' on the right side of this banner should dismiss it.
- Refreshing, loading another page, logging out / in again should not show the banner
#1385 
@jagtalon 
No

Supporting backend elements to dismiss ddh profile notification

---

lib/DDGC/Web/Controller/InstantAnswer.pm
t/instant_answer_basics.t

IDs (and meta_ids) should always be case insensitive, but the format_id() function wasn't called in (here)[https://github.com/duckduckgo/community-platform/blob/master/lib/DDGC/Web/Controller/InstantAnswer.pm#L1259], which allowed people to use uppercase in their IDs when creating an IA Page from a PR.
Just added a call to that function in there, it was an easy fix.
When creating an IA Page from the new IA wizard (ia/new_ia), both when filling in the fields and when skipping the wizard by using a PR link, the resulting meta_id for should always be all lowercase.
[This](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3134) was the PR used to create the IA Page with the uppercase ID, but it's fixed now.
#
@moollaza @tagawa 

InstantAnswer.pm - call format_id() inside create_ia_from_pr()

---

root/static/pages/ddh_up_index.html

Since JS needs to execute and fetch the data, the markup in the `<title>` tag is recorded in the history. To get around it, I used the ngBind directive to replace the text inside the tag once the data is available instead of using the template markup.

Use ngBind to replace the <title>

---

templates/notice_campaign.tx

Part of the markup was missing, probably mistakenly deleted in the past few days while making other changes.
Log in with GitHub, keeping the network panel of the dev tools open to verify the request is sent when the banner is shown
#

notice_campaign.tx - bring back lost markup

---

lib/DDGC/Web/Controller/InstantAnswer.pm
t/instant_answer_basics.t

Redirect to the correct IA Page even if the meta_id in the URL contains uppercase chars.
How to test this manually: 
- manually type a single IA Page URL containing one or more uppercase letters. Does it load the correct IA Page?
- Now type the URL for the same IA Page, but using the lowercase meta_id. Does it still load the correct IA Page?
#
@tagawa @russellholt 

IA Pages - find the correct IA regardless of letter casing in the URL

---

src/templates/commit_page.handlebars

Don't linkify maintainer and devs so it's easier to select the change to commit.
Try changing the devs and maintainer values and go to the commit page. Expected: text only, no links.
#

Commit Page - don't linkify maintainer and devs

---

lib/DDGC/Web/Controller/InstantAnswer.pm
t/instant_answer_basics.t

Fixes a bug with giving edit permissions to the maintainer when the IA is not yet live.
The culprit is we required the edit to be committed, and didn't take into account autocommitting, when assigning permissions, so it worked only for live IAs.
I wrote a back-end test for this in instant_answers_basics.t but you can also test it manually by logging in as admin, changing the maintainer of a live IA and an IA in development to another non-admin user in your instance (it needs to have a GitHub account connected though), log out, log in again as the non-admin user, load again the pages and see if you have edit permissions for them.
#
@moollaza 
I'd like to stage the changes and then deploy to prod either today or tomorrow after this is merged.

Dev IA Pages - fix assigning edit permissions to the maintainer

---

script/ghIssues.pl

Updates the IA page regex to only match certain contexts, so we don't incorrectly infer which IA the PR/issue belongs to.
Fixes #1371 
@jdorweiler 
I really hope not.

Update IA page regex to match standard format

---

src/js/ia/IAPageCommit.js
src/templates/commit_page.handlebars

Fixes an issue with DDH profile URLs not showing on the IA Pages for contributors, when they're added manually.
There was a missing parameter, the URL, not being sent to the backend on commit - the issue affects the live IA Pages.
#
@jbarrett 
I need to deploy this asap as hotfix

Commit Page - send developer account URL to the backend

---

script/ghIssues.pl

Updated the regex that finds IA page links in the first post of issues and pull requests. I updated it to be a little more forgiving by allowing extra spaces before the url and pulling off trailing spaces after the url.
cc/ @GuiltyDolphin

update ia page regex

---

lib/DDGC/Base/Web/Light.pm
lib/DDGC/Schema/Result/Subscriber.pm
lib/DDGC/Schema/Result/Subscriber/MailLog.pm
lib/DDGC/Schema/ResultSet/Subscriber.pm
lib/DDGC/Util/Email.pm
lib/DDGC/Util/Script/SubscriberMailer.pm
lib/DDGC/Web/App/Subscriber.pm
lib/Dancer2/Plugin/DDGC/Config.pm
script/ddgc_dev_server.psgi
script/ddgc_subscriber_mail.pl
sql/1.189/subscriber.sql
t/subscribers.t
views/email/a/1.tx
views/email/a/2.tx
views/email/a/3.tx
views/email/a/4.tx
views/email/a/5.tx
views/email/a/6.tx
views/email/a/7.tx
views/email/a/v.tx

This PR is an application to manage regular mail outs to verified email addresses:
- Web app to add, verify and remove subscriptions
- Script wrapper to send verification and scheduled mails
Unit tests incoming.
- New DDL in sql/1.189/subscriber.sql
- Add subscriber with:
````bash
curl -o /dev/null --data "campaign=a&email=<your email>" http://localhost:5001/s/a
```
- Send verification email with:
```bash
script/ddgc_subscriber_mail.pl --verify
```
- Send mail for a given date with (e.g. for tomorrow):
```bash
script/ddgc_subscriber_mail.pl --mock_date=2016-10-19
```
- Only a verified email address should receive email
- Unsubscribed emails should not receive any email
- There are 6 mail shots configured for every two days from tomorrow (or the day after subscription)
- Unsubscribe and …

Subscriber management and mailer jobs

---

sql/1.195/live_fatheads.pl

There are many live fatheads that don't have the correct production state set. We're going to actually start using production state for fatheads. This sets all live fatheads to the correct production state.

update live fatheads

---

templates/translate/domainindex.tx
templates/translate/index.tx

Commenting out the call for translation managers because this is not our focus at the moment.
Note that my editor removed lots of trailing spaces.
@jbarrett 
Nope

Hiding the call for translation managers

---

lib/DDGC/Schema/Result.pm
lib/DDGC/Schema/Result/Subscriber.pm
t/subscribers.t

This change updates the signup date for subscribers when their address has been verified 
Unit tests have been updated, but the major change is that the created date for a subscriber row should be updated to `now()` matching the date the verification link was clicked.
@yegg @AdamSC1-ddg @MariagraziaAlastra 
No privacy changes

Shift subscription schedule to date of email verification

---

lib/DDGC/Feedback/Config/Suggest.pm
lib/DDGC/Web/Controller/Comment.pm
lib/DDGC/Web/Controller/Feedback.pm
templates/forum/share_suggestion.tx
templates/i/comment/thread.tx
templates/i/comment/view.tx
templates/i/comment_add.tx

This change should disallow further posting on the forum on duck.co. It has a mixture of template and backend changes:
- New thread links removed
- Reply links removed
- Reply text boxes removed 
It should no longer be possible to create new posts or replies in forum / ideas.
Posting replies on blog posts, translation pages should still work.
https://duck.co/forum/thread/27632/staff-notice-forum-closing-in-january-2017
@tagawa 
Nope.

Close forum posting functions

---

lib/DDGC/Web/App/Subscriber.pm
t/subscribers.t

While this isn't strictly necessary, since we currently verify email addresses by emailing them, the possibility arises that our provider doesn't like us sending them trash envelopes.
This change silently drops POSTs which plainly aren't email addresses. The front end uses an ["email" type input element which is pretty much universally supported](http://caniuse.com/#search=email), so feeding back actual error conditions won't achieve much beyond this.
- /s/form has a test form to submit addresses
- Submit a valid email address:
- HTTP 200, content 'OK'
- address appears in subscriber table
- Submit an invalid email address:
- HTTP 200, content empty
- address does not appear in subscriber table
[Email::Valid](https://metacpan.org/pod/Email::Valid) is used to filter addresses. This is …

Silently drop invalid subscriber email addresses

---

cpanfile
lib/DDGC/Base/Web/LightService.pm
lib/DDGC/Schema/Result/Subscriber.pm
lib/DDGC/Schema/ResultSet/Subscriber.pm
lib/DDGC/Schema/ResultSet/User.pm
lib/DDGC/Util/Script/SubscriberMailer.pm
lib/DDGC/Web/Service/Bounce.pm
lib/Dancer2/Plugin/DDGC/Config.pm
lib/Dancer2/Plugin/DDGC/Service.pm
script/ddgc_dev_server.psgi
sql/1.203/bounces.sql
t/bounces.t
t/lib/DDGC/TestUtils/AWS.pm
t/sns_verify.t

Service to remove subscribers, acting upon bounce notifications from SNS.
- Schema change in sql/1.203/bounces.sql
- ...
@yegg @AdamSC1-ddg 
This PR introduces additional facilities to verify users and respect user privacy.
New CPAN dependencies:
```
+requires 'Ouch', '0.0410';
+requires 'Crypt::OpenSSL::X509' '1.804';
+requires 'Crypt::OpenSSL::Random' '0.11';
+requires 'Crypt::OpenSSL::RSA' '0.28';
+requires 'AWS::SNS::Verify' '0.0102';
```
New service definition will be created elsewhere.

Bounce handling via SNS

---

lib/DDGC/Schema/ResultSet/Subscriber.pm
lib/DDGC/Util/Script/SubscriberMailer.pm
t/subscribers.t

We will have instances where mail shots will have minor differences between runs. This adds support for defining additional campaigns which are mostly the same as another. You define the new one with a base (existing campaign you want to base the new one on) and any differences between them.
TBD
@yegg @AdamSC1-ddg 
No

Support for mail lists based on other lists with minor changes

---

lib/DDGC/Util/Email.pm
script/coverage_alert.pl
views/email/translation_counts.tx

Email percentage coverage alerts to specified addresses
In dev:
```
$ script/coverage_alert.pl --email=[your address] --domain=test
```
...should email you a short report on german and french coverage on the test domain. These numbers should match the translation frontend.
#

Translation coverage email

---

script/ghIssues.pl

Stop setting tab name for fatheads and goodies in ghIssues.pl
Setting the tab name in ghIssues (for goodies at least) overrides more useful ones which should be made to stand out, such as Calculator.
#
@jdorweiler @russellholt @MariagraziaAlastra @jkv @moollaza @bsstoner @pjhampton
No

Stop setting tab name in ghIssues

---

script/ddgc_upload_metadata.sh

Additional validation and upload stages for metadata upload
- JSON validity
- bzip file validity
- Atomic set-and-move depending on s3cmd success
#
@jkv @kablamo 

Add additional checks to metadata upload script

---

lib/DDGC/Config.pm
lib/DDGC/Web/Controller/Feedback.pm
templates/email/base.tx
templates/email/feedback.tx
templates/feedback/option/next.tx

Bypass support address for security issues coming through feedback system
Set `DDGC_DIRECTLINE_EMAIL` in env and visit /feedback/bug to begin a security report. Report should go to the address you set in the env.
#
@jkv @MariagraziaAlastra 

Bypass support@ for security reports

---

lib/DDGC/Web/Controller/Root.pm

Do not apply session invalidation rules to basic auth requests since this can break duck workflow.
#

Do not apply session invalidation rules to basic auth requests

---

lib/DDGC/Web/Controller/Help.pm

Do not show empty help categories on help pages
Yes, this should be done in the query but this isn't significantly slower and allows me to not have to think about it.
- Removing or changing the `cache_for` value to 0 on line 17 should make testing this easier
- Using the help editor in /admin/help, remove all help articles from a given category
- This category should no longer be visible on /help or the side menu on help pages
- Re-adding articles to this category should show them again on these pages
#
@tagawa 
Nah - grepping across a handful of rows is fast enough.

Filter out categories with no related helps

---

lib/DDGC/Feedback/Config/Feature.pm

In our feedback flow, we're currently sending people with feature ideas to the old (closed) forum. This PR changes that to the DDG subreddit.
#
@moollaza 
No

Removed links to old forum

---

root/static/css/content.css

Have added styles to the end of content.css to override existing styles and keep them grouped together. These mostly apply brand colours to duck.co, focusing on the help pages, with the intention of making it more consistent with https://duckduckgo.com/traffic and https://duckduckgo.com/hiring
Although designed for the help pages, also needs testing in /translate and the archived forum and blog. Oh, and user account pages too.
#
@jbarrett @MariagraziaAlastra 
No security/privacy or performance implications. Does affect (and may break) the appearance.

Design refresh for better consistency

---

root/static/css/content.css

Added a darker shade of blue when buttons are hovered over or in focus.
#
@jbarrett @chrismorast 

Added :hover colour change to blue buttons

---

root/static/css/content.css

Removes some strange padding in the login box (translation page only).
#
@jbarrett @chrismorast 
No

Fixed extra padding on translate login page

---

lib/DDGC/PagerDuty.pm

@jbarrett, we need to switch to using PagerDuty v2 as v1 will stop working soon. Can you review/test this?
#

Switch to using PagerDuty v2 API

---

lib/DDGC/DB/Result/Token/Domain/Language.pm
lib/DDGC/DB/ResultSet/Token/Language.pm
lib/DDGC/LocaleDist.pm
lib/DDGC/Web/Controller/Translate.pm
src/js/ddgc/ddgc.js
t/translation.t
templates/translate/tokens/token_language.tx

This change should add a simple facility for admins to retire translation tokens which are no longer in use.
These tokens should not be counted in coverage metrics, should not show up in "unvoted" or "untranslated" sets and should not be included in published locale packages.
A new button should be visible to admins on translation pages - Retire or Un-retire a token.
A message should be visible to non-admins to let them know a token has been retired.
Retired tokens should not show up in untranslated or unvoted work flows.
New unit tests assert that retired tokens are not published to locale packages. If you wish to verify this you can run (e.g. for the test domain in dev):
```bash
script/ddgc_update_locale_dist.pl --domain=test
```
The output of this script will give you a filename with …

Adding support to retire translation tokens

---

lib/DDGC/DB/Result/Token/Domain/Language.pm
t/translation.t

This removes translations completely for en_US.
See locale updating notes in #1508
po and js files should be created for en_US which means gettext will still be built for it, but no tokens/translations should be present in the file.
#1508 
@bsstoner @andrey-p @tagawa 

Don't publish translations for en_US

---

script/ddgc_update_locale_dist.pl

Do not publish locale package if there has not been a new translation or vote in 12 hours
(Providing you have made no translation changes in the last 12h):
1. This will skip publishing the package:
`$ script/ddgc_update_locale_dist.pl --domain=test`
2. You can force it to update:
`$ script/ddgc_update_locale_dist.pl --domain=test --force`
3. Go to /translate/test and add or vote on a translation, then publish without force publishes a package:
`$ script/ddgc_update_locale_dist.pl --domain=test`
4. Wait a few seconds and try with a different delta - this should skip publish:
`$ script/ddgc_update_locale_dist.pl --domain=test --delta=5s`
#

Skip updating locale package if no update in last 12h

---

lib/DDGC/Web/Controller/InstantAnswer.pm
src/js/ia/IADevPipeline.js
src/js/ia/IAPage.js
src/templates/dev_pipeline.handlebars
src/templates/dev_pipeline_actions.handlebars
src/templates/dev_pipeline_detail.handlebars
src/templates/devinfo.handlebars
src/templates/overview.handlebars

change JSON API URL to the new one, retire beta installation code on the backend and frontend.
@kablamo @jkv @moollaza @jdorweiler @tagawa 
We'll test this for a day and assuming nothing unexpected breaks, we'll keep the change.
This might make the dev pipeline inaccurate going forward (especially the "Testing" column) and might also break the "generate screenshot" button in the single IA Pages.
1. Populate the IA DB if not done already by running script/ddgc_populate_ia_dev.pl
2. run grunt
3. script/ddgc_dev_server.sh
4. On the instance, verify the following paths: /ia (shows list of IAs), /ia/dev/pipeline (Dev Pipeline), single IA Pages - they should all  be populated and looking like in prod
5. Log in as admin (TestOne) and go to single IA Page live and also in development - there …

Retire code relying on beta server

---

src/scss/ia/_new.scss

We removed `$blue-lightest` here: https://github.com/duckduckgo/duckduckgo-colors/pull/6/files
This PR just removes the reference and creates the color locally here.
/cc @bbraithwaite

Remove ref to blue-lightest

---

lib/DDGC/Web.pm

Since this software considers events like CSRF failures and missing help articles as critical failures, crash mail is close to useless.
This change disables crash mail.
Dev nodes aren't set up for this, so we'll likely need to stage it to verify functionality.
Test plan:
- Contrive a "crash" by tampering the CSRF token in the login form.
- No email is sent
#

Remove Catalyst::Plugin::ErrorCatcher::Email

---

templates/my/account.tx

Hides XMPP information in user account pages. Tested in Firefox, Vivaldi and Safari.
#
@jbarrett @MariagraziaAlastra 
Nope
- [N/A] Back end tests (perl, scripts)

Hides XMPP information in user account pages

---

lib/DDGC/DB/Result/Token/Language.pm
t/translation.t

Add token notes as extracted comments in generated po files. 
- Log in as admin (TestOne)
- Add some notes in the translation interface for a token in the 'test' domain
- `script/ddgc_update_locale_dist.pl -f --domain=test`
- New package in : `/home/ddgc/ddgc/duckpan/authors/id/T/TE/TESTONE/`
- For each language, share/$lang/LC_MESSAGES/test.po should contain your notes prefixed with `#.` (extracted comment)
- These comments should not be in js files.
More info on locale package evaluation in #1508 
#
N

Add extracted comments to po files from token notes

---

root/static/css/content.css

Restoring changes to duck.co design (CSS only) from November 2017.
The [history of this file](https://github.com/duckduckgo/community-platform/commits/master/root/static/css/content.css) shows there's been [one change since then](https://github.com/duckduckgo/community-platform/commit/e0b14b1bc16dba9d8a1e2eee8b9c64450bd035a7#diff-64a612c667686eae6bf77ba7505abd89), which didn't change the code being restored here.
For reference, here are the previously merged PRs:
* https://github.com/duckduckgo/community-platform/pull/1500
* https://github.com/duckduckgo/community-platform/pull/1502
* https://github.com/duckduckgo/community-platform/pull/1503
* https://github.com/duckduckgo/community-platform/pull/1504
@jbarrett 
Don't think so.

Restoring previous design tweaks

---

lib/DDGC/Feedback/Config/Bug.pm

Some pages still link to the feedback bug flow. This change links the 'security issue' option straight to hackerone.
- Visit `/feedback/bug/-` and click "It's a security issue"
- You should be redirected to the DDG hackerone page.
#
@marcantonio @isaddg 

Change security issue flow to link to hackerone
